<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{

    public function run()
    {
        DB::table('companies')->insert([
            [
                'company_id'        => 'C001',
                'page_id'           => 'COM',
                'name'              => 'Microsoft',
                'sector'            => 'Private Company',
                'industry'          => 'Software Development',
                'tagline'           => 'Empower every person and every organization on the planet to achieve more',
                'established_date'  => '1975-04-04',
                'country'           => 'United States',
                'city'              => 'Redmond, Washington',
                'website'           => 'https://microsoft.com/id-id',
                'employee'          => '10451',
                'logo'              => 'microsoft.jpg',
                'cover_image'       => 'microsoft.jpg',
            ],
            [
                'company_id'        => 'C002',
                'page_id'           => 'COM',
                'name'              => 'Meta',
                'sector'            => 'Private Company',
                'industry'          => 'Social Networking Software',
                'tagline'           => 'Connection is evolving and so are we',
                'established_date'  => '2004-02-04',
                'country'           => 'United States',
                'city'              => 'California',
                'website'           => 'https://meta.com/',
                'employee'          => '12091',
                'logo'              => 'meta.jpg',
                'cover_image'       => 'meta.jpg',
            ],
            [
                'company_id'        => 'C003',
                'page_id'           => 'COM',
                'name'              => 'Facebook',
                'sector'            => 'Private Company',
                'industry'          => 'Social Networking Software',
                'tagline'           => 'Connect with friends and the world around you on Facebook',
                'established_date'  => '2004-02-04',
                'country'           => 'United States',
                'city'              => 'California',
                'website'           => 'https://facebook.com/',
                'employee'          => '8520',
                'logo'              => 'facebook.jpg',
                'cover_image'       => 'facebook.jpg',
            ],
            [
                'company_id'        => 'C004',
                'page_id'           => 'COM',
                'name'              => 'Instagram',
                'sector'            => 'Private Company',
                'industry'          => 'Social Networking Software',
                'tagline'           => 'Bringing you closer to the people and things you love',
                'established_date'  => '2010-10-06',
                'country'           => 'United States',
                'city'              => 'California',
                'website'           => 'https://instagram.com/',
                'employee'          => '7825',
                'logo'              => 'instagram.jpg',
                'cover_image'       => 'instagram.jpg',
            ],
            [
                'company_id'        => 'C005',
                'page_id'           => 'COM',
                'name'              => 'Apple',
                'sector'            => 'Private Company',
                'industry'          => 'Computers and Electronics Manufacturing',
                'tagline'           => 'Think Different',
                'established_date'  => '1976-04-01',
                'country'           => 'United States',
                'city'              => 'California',
                'website'           => 'https://apple.com/',
                'employee'          => '13550',
                'logo'              => 'apple.jpg',
                'cover_image'       => 'apple.jpg',
            ],
            [
                'company_id'        => 'C006',
                'page_id'           => 'COM',
                'name'              => 'GoTo Group',
                'sector'            => 'Private Company',
                'industry'          => 'Software Development',
                'tagline'           => 'Go Far, Go Together',
                'established_date'  => '2021-05-17',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://gotocompany.com/',
                'employee'          => '5800',
                'logo'              => 'goto.jpg',
                'cover_image'       => 'goto.jpg',
            ],
            [
                'company_id'        => 'C007',
                'page_id'           => 'COM',
                'name'              => 'Tokopedia',
                'sector'            => 'Private Company',
                'industry'          => 'E-Commerce Software',
                'tagline'           => 'Empowering everyone to start and grow',
                'established_date'  => '2009-08-17',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://tokopedia.com',
                'employee'          => '3925',
                'logo'              => 'tokopedia.jpg',
                'cover_image'       => 'tokopedia.jpg',
            ],
            [
                'company_id'        => 'C008',
                'page_id'           => 'COM',
                'name'              => 'Gojek',
                'sector'            => 'Private Company',
                'industry'          => 'Courier Software',
                'tagline'           => 'Everyday solutions, one app away',
                'established_date'  => '2010-12-05',
                'country'           => 'Indonesia',
                'city'              => 'South Jakarta',
                'website'           => 'https://gojek.com/',
                'employee'          => '4250',
                'logo'              => 'gojek.jpg',
                'cover_image'       => 'gojek.jpg',
            ],
            [
                'company_id'        => 'C009',
                'page_id'           => 'EDU',
                'name'              => 'BINUS University',
                'sector'            => 'Private Company',
                'industry'          => 'Higher Education',
                'tagline'           => 'Fostering and Empowering the Society in Building and Serving the Nation',
                'established_date'  => '1981-06-01',
                'country'           => 'Indonesia',
                'city'              => 'West Jakarta',
                'website'           => 'https://binus.ac.id/',
                'employee'          => '2530',
                'logo'              => 'binus.jpg',
                'cover_image'       => 'binus.jpg',
            ],
            [
                'company_id'        => 'C010',
                'page_id'           => 'EDU',
                'name'              => 'BINUS School',
                'sector'            => 'Private Company',
                'industry'          => 'Primary and Secondary Education',
                'tagline'           => 'Fostering and Empowering the Society in Building and Serving the Nation',
                'established_date'  => '2001-03-25',
                'country'           => 'Indonesia',
                'city'              => 'West Jakarta',
                'website'           => 'https://binus.sch.id/',
                'employee'          => '1450',
                'logo'              => 'binus_school.jpg',
                'cover_image'       => 'binus_school.jpg',
            ],
            [
                'company_id'        => 'C011',
                'page_id'           => 'EDU',
                'name'              => 'Harvard University',
                'sector'            => 'Private Company',
                'industry'          => 'Higher Education',
                'tagline'           => 'Pursuing truth. Shaping the future',
                'established_date'  => '1636-10-28',
                'country'           => 'United States',
                'city'              => 'Cambridge',
                'website'           => 'https://harvard.edu/',
                'employee'          => '10250',
                'logo'              => 'harvard.jpg',
                'cover_image'       => 'harvard.jpg',
            ],
            [
                'company_id'        => 'C012',
                'page_id'           => 'COM',
                'name'              => 'Ubisoft',
                'sector'            => 'Private Company',
                'industry'          => 'Computer Games',
                'tagline'           => 'Creating worlds of fun and adventure',
                'established_date'  => '1986-03-28',
                'country'           => 'France',
                'city'              => 'Saint Mande',
                'website'           => 'https://ubisoft.com/',
                'employee'          => '14500',
                'logo'              => 'ubisoft.jpg',
                'cover_image'       => 'ubisoft.jpg',
            ],
            [
                'company_id'        => 'C013',
                'page_id'           => 'COM',
                'name'              => 'Bank Central Asia',
                'sector'            => 'Private Company',
                'industry'          => 'Banking',
                'tagline'           => 'Trusted partner for your financial journey',
                'established_date'  => '1957-02-21',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://bca.co.id/',
                'employee'          => '12350',
                'logo'              => 'bca.jpg',
                'cover_image'       => 'bca.jpg',
            ],
            [
                'company_id'        => 'C014',
                'page_id'           => 'COM',
                'name'              => 'Pertamina',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Energy & Petroleum',
                'tagline'           => 'Energizing the Nation',
                'established_date'  => '1957-12-10',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://pertamina.com/',
                'employee'          => '43000',
                'logo'              => 'pertamina.jpg',
                'cover_image'       => 'pertamina.jpg',
            ],
            [
                'company_id'        => 'C015',
                'page_id'           => 'COM',
                'name'              => 'PLN',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Electricity',
                'tagline'           => 'Powering Indonesia Forward',
                'established_date'  => '1965-01-01',
                'country'           => 'Indonesia',
                'city'              => 'South Jakarta',
                'website'           => 'https://pln.co.id/',
                'employee'          => '53000',
                'logo'              => 'pln.jpg',
                'cover_image'       => 'pln.jpg',
            ],
            [
                'company_id'        => 'C016',
                'page_id'           => 'COM',
                'name'              => 'Telkom Indonesia',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Telecommunications',
                'tagline'           => 'The World in Your Hand',
                'established_date'  => '1965-07-23',
                'country'           => 'Indonesia',
                'city'              => 'Bandung',
                'website'           => 'https://telkom.co.id/',
                'employee'          => '24000',
                'logo'              => 'telkom.jpg',
                'cover_image'       => 'telkom.jpg',
            ],
            [
                'company_id'        => 'C017',
                'page_id'           => 'COM',
                'name'              => 'Bank Mandiri',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Banking',
                'tagline'           => 'Terdepan, Terpercaya, Tumbuh Bersama Anda',
                'established_date'  => '1998-10-02',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://bankmandiri.co.id/',
                'employee'          => '39000',
                'logo'              => 'mandiri.jpg',
                'cover_image'       => 'mandiri.jpg',
            ],
            [
                'company_id'        => 'C018',
                'page_id'           => 'COM',
                'name'              => 'BRI (Bank Rakyat Indonesia)',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Banking',
                'tagline'           => 'Melayani Dengan Setulus Hati',
                'established_date'  => '1895-12-16',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://bri.co.id/',
                'employee'          => '90000',
                'logo'              => 'bri.jpg',
                'cover_image'       => 'bri.jpg',
            ],
            [
                'company_id'        => 'C019',
                'page_id'           => 'COM',
                'name'              => 'BNI (Bank Negara Indonesia)',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Banking',
                'tagline'           => 'Melayani Negeri, Kebanggaan Bangsa',
                'established_date'  => '1946-07-05',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://bni.co.id/',
                'employee'          => '27000',
                'logo'              => 'bni.jpg',
                'cover_image'       => 'bni.jpg',
            ],
            [
                'company_id'        => 'C020',
                'page_id'           => 'COM',
                'name'              => 'KAI (Kereta Api Indonesia)',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Transportation',
                'tagline'           => 'We Serve Better',
                'established_date'  => '1945-09-28',
                'country'           => 'Indonesia',
                'city'              => 'Bandung',
                'website'           => 'https://kai.id/',
                'employee'          => '30000',
                'logo'              => 'kai.jpg',
                'cover_image'       => 'kai.jpg',
            ],
            [
                'company_id'        => 'C021',
                'page_id'           => 'COM',
                'name'              => 'Garuda Indonesia',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Aviation',
                'tagline'           => 'A World-Class Airline',
                'established_date'  => '1949-01-26',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'website'           => 'https://garuda-indonesia.com/',
                'employee'          => '6500',
                'logo'              => 'garuda.jpg',
                'cover_image'       => 'garuda.jpg',
            ],
            [
                'company_id'        => 'C022',
                'page_id'           => 'COM',
                'name'              => 'Waskita Karya',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Construction',
                'tagline'           => 'Building a Better Future',
                'established_date'  => '1961-01-01',
                'country'           => 'Indonesia',
                'city'              => 'East Jakarta',
                'website'           => 'https://waskita.co.id/',
                'employee'          => '8000',
                'logo'              => 'waskita.jpg',
                'cover_image'       => 'waskita.jpg',
            ],
            [
                'company_id'        => 'C023',
                'page_id'           => 'COM',
                'name'              => 'Pelindo (Pelabuhan Indonesia)',
                'sector'            => 'State-Owned Enterprise (SOE)',
                'industry'          => 'Port & Logistics',
                'tagline'           => 'Connecting the Nation',
                'established_date'  => '1960-12-01',
                'country'           => 'Indonesia',
                'city'              => 'North Jakarta',
                'website'           => 'https://pelindo.co.id/',
                'employee'          => '11000',
                'logo'              => 'pelindo.jpg',
                'cover_image'       => 'pelindo.jpg',
            ],
            [
                'company_id'        => 'C024',
                'page_id'           => 'COM',
                'name'              => 'Astra International',
                'sector'            => 'Private Company',
                'industry'          => 'Automotive & Conglomerate',
                'tagline'           => 'Empowering Indonesia through sustainable mobility and innovation',
                'established_date'  => '1957-06-20',
                'country'           => 'Indonesia',
                'city'              => 'Jakarta Selatan',
                'website'           => 'https://www.astra.co.id/',
                'employee'          => '210000',
                'logo'              => 'astra.jpg',
                'cover_image'       => 'astra-cover.jpg',
            ],
            [
                'company_id'        => 'C025',
                'page_id'           => 'COM',
                'name'              => 'Sinar Mas Group',
                'sector'            => 'Private Company',
                'industry'          => 'Conglomerate',
                'tagline'           => 'Growing businesses that strengthen Indonesia',
                'established_date'  => '1962-01-01',
                'country'           => 'Indonesia',
                'city'              => 'Jakarta Pusat',
                'website'           => 'https://www.sinarmas.com/',
                'employee'          => '380000',
                'logo'              => 'sinar_mas.jpg',
                'cover_image'       => 'sinar_mas-cover.jpg',
            ],
            [
                'company_id'        => 'C026',
                'page_id'           => 'COM',
                'name'              => 'Gudang Garam',
                'sector'            => 'Private Company',
                'industry'          => 'Manufacturing (Tobacco)',
                'tagline'           => 'One of Indonesia’s largest consumer goods manufacturers',
                'established_date'  => '1958-06-26',
                'country'           => 'Indonesia',
                'city'              => 'Kediri',
                'website'           => 'https://www.gudanggaramtbk.com/',
                'employee'          => '36000',
                'logo'              => 'gudang_garam.jpg',
                'cover_image'       => 'gudang_garam-cover.jpg',
            ],
            [
                'company_id'        => 'C027',
                'page_id'           => 'COM',
                'name'              => 'Mayora Indah',
                'sector'            => 'Private Company',
                'industry'          => 'Food & Beverage',
                'tagline'           => 'A global FMCG leader bringing Indonesia’s favorite brands to the world',
                'established_date'  => '1977-02-17',
                'country'           => 'Indonesia',
                'city'              => 'Tangerang',
                'website'           => 'https://www.mayoraindah.co.id/',
                'employee'          => '12000',
                'logo'              => 'mayora.jpg',
                'cover_image'       => 'mayora-cover.jpg',
            ],
            [
                'company_id'        => 'C028',
                'page_id'           => 'COM',
                'name'              => 'Kalbe Farma',
                'sector'            => 'Private Company',
                'industry'          => 'Pharmaceutical',
                'tagline'           => 'Advancing health for a better life',
                'established_date'  => '1966-09-10',
                'country'           => 'Indonesia',
                'city'              => 'Jakarta Timur',
                'website'           => 'https://www.kalbe.co.id/',
                'employee'          => '17000',
                'logo'              => 'kalbe.jpg',
                'cover_image'       => 'kalbe-cover.jpg',
            ],
            [
                'company_id'        => 'C029',
                'page_id'           => 'COM',
                'name'              => 'Perum BULOG',
                'sector'            => 'SOE',
                'industry'          => 'Logistics & Food Security',
                'tagline'           => 'Ensuring national food security for all Indonesians',
                'established_date'  => '1967-05-10',
                'country'           => 'Indonesia',
                'city'              => 'Jakarta Timur',
                'website'           => 'https://www.bulog.co.id/',
                'employee'          => '9500',
                'logo'              => 'bulog.jpg',
                'cover_image'       => 'bulog-cover.jpg',
            ],
            [
                'company_id'        => 'C030',
                'page_id'           => 'COM',
                'name'              => 'PT Pindad (Persero)',
                'sector'            => 'SOE',
                'industry'          => 'Defense Manufacturing',
                'tagline'           => 'Advanced defense technology for national resilience',
                'established_date'  => '1983-04-29',
                'country'           => 'Indonesia',
                'city'              => 'Bandung',
                'website'           => 'https://www.pindad.com/',
                'employee'          => '3500',
                'logo'              => 'pindad.jpg',
                'cover_image'       => 'pindad-cover.jpg',
            ],
            [
                'company_id'        => 'C031',
                'page_id'           => 'COM',
                'name'              => 'PT Dirgantara Indonesia',
                'sector'            => 'SOE',
                'industry'          => 'Aerospace Manufacturing',
                'tagline'           => 'Leading aerospace innovation in Southeast Asia',
                'established_date'  => '1976-08-23',
                'country'           => 'Indonesia',
                'city'              => 'Bandung',
                'website'           => 'https://www.indonesian-aerospace.com/',
                'employee'          => '4200',
                'logo'              => 'dirgantara.jpg',
                'cover_image'       => 'dirgantara-cover.jpg',
            ],
            [
                'company_id'        => 'C032',
                'page_id'           => 'COM',
                'name'              => 'PT PAL Indonesia',
                'sector'            => 'SOE',
                'industry'          => 'Shipbuilding & Marine Engineering',
                'tagline'           => 'Building world-class naval and commercial vessels',
                'established_date'  => '1980-04-15',
                'country'           => 'Indonesia',
                'city'              => 'Surabaya',
                'website'           => 'https://www.pal.co.id/',
                'employee'          => '2800',
                'logo'              => 'pal.jpg',
                'cover_image'       => 'pal-cover.jpg',
            ],
            [
                'company_id'        => 'C033',
                'page_id'           => 'COM',
                'name'              => 'PT Len Industri',
                'sector'            => 'SOE',
                'industry'          => 'Electronics & Defense Systems',
                'tagline'           => 'Empowering defense and transportation with advanced electronics',
                'established_date'  => '1991-09-12',
                'country'           => 'Indonesia',
                'city'              => 'Bandung',
                'website'           => 'https://www.len.co.id/',
                'employee'          => '1800',
                'logo'              => 'len.jpg',
                'cover_image'       => 'len-cover.jpg',
            ],


        ]);
    }
}
