<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    
    public function run()
    {
        DB::table('companies')->insert([
            [
                'company_id'        => 'C001',
                'page_id'           => 'COM',
                'name'              => 'Microsoft',
                'industry'          => 'Software Development',
                'tagline'           => 'Empower every person and every organization on the planet to achieve more',
                'established_date'  => '1975-04-04',
                'country'           => 'United States',
                'city'              => 'Redmond, Washington',
                'logo'              => 'microsoft.jpg',
                'cover_image'       => 'microsoft.jpg',
            ],
            [
                'company_id'        => 'C002',
                'page_id'           => 'COM',
                'name'              => 'Meta',
                'industry'          => 'Social Networking Software',
                'tagline'           => 'Connection is evolving and so are we',
                'established_date'  => '2004-02-04',
                'country'           => 'United States',
                'city'              => 'California',
                'logo'              => 'meta.jpg',
                'cover_image'       => 'meta.jpg',
            ],
            [
                'company_id'        => 'C003',
                'page_id'           => 'COM',
                'name'              => 'Facebook',
                'industry'          => 'Social Networking Software',
                'tagline'           => 'Connect with friends and the world around you on Facebook',
                'established_date'  => '2004-02-04',
                'country'           => 'United States',
                'city'              => 'California',
                'logo'              => 'facebook.jpg',
                'cover_image'       => 'facebook.jpg',
            ],
            [
                'company_id'        => 'C004',
                'page_id'           => 'COM',
                'name'              => 'Instagram',
                'industry'          => 'Social Networking Software',
                'tagline'           => 'Bringing you closer to the people and things you love',
                'established_date'  => '2010-10-06',
                'country'           => 'United States',
                'city'              => 'California',
                'logo'              => 'instagram.jpg',
                'cover_image'       => 'instagram.jpg',
            ],
            [
                'company_id'        => 'C005',
                'page_id'           => 'COM',
                'name'              => 'Apple',
                'industry'          => 'Computers and Electronics Manufacturing',
                'tagline'           => 'Think Different',
                'established_date'  => '1976-04-01',
                'country'           => 'United States',
                'city'              => 'California',
                'logo'              => 'apple.jpg',
                'cover_image'       => 'apple.jpg',
            ],
            [
                'company_id'        => 'C006',
                'page_id'           => 'COM',
                'name'              => 'GoTo Group',
                'industry'          => 'Software Development',
                'tagline'           => 'Go Far, Go Together',
                'established_date'  => '2021-05-17',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'logo'              => 'goto.jpg',
                'cover_image'       => 'goto.jpg',
            ],
            [
                'company_id'        => 'C007',
                'page_id'           => 'COM',
                'name'              => 'Tokopedia',
                'industry'          => 'E-Commerce Software',
                'tagline'           => 'Empowering everyone to start and grow',
                'established_date'  => '2009-08-17',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'logo'              => 'tokopedia.jpg',
                'cover_image'       => 'tokopedia.jpg',
            ],
            [
                'company_id'        => 'C008',
                'page_id'           => 'COM',
                'name'              => 'Gojek',
                'industry'          => 'Courier Software',
                'tagline'           => 'Everyday solutions, one app away',
                'established_date'  => '2010-12-05',
                'country'           => 'Indonesia',
                'city'              => 'South Jakarta',
                'logo'              => 'gojek.jpg',
                'cover_image'       => 'gojek.jpg',
            ],
            [
                'company_id'        => 'C009',
                'page_id'           => 'EDU',
                'name'              => 'BINUS University',
                'industry'          => 'Higher Education',
                'tagline'           => 'Fostering and Empowering the Society in Building and Serving the Nation',
                'established_date'  => '1981-06-01',
                'country'           => 'Indonesia',
                'city'              => 'West Jakarta',
                'logo'              => 'binus.jpg',
                'cover_image'       => 'binus.jpg',
            ],
            [
                'company_id'        => 'C010',
                'page_id'           => 'EDU',
                'name'              => 'BINUS School',
                'industry'          => 'Primary and Secondary Education',
                'tagline'           => 'Fostering and Empowering the Society in Building and Serving the Nation',
                'established_date'  => '2001-03-25',
                'country'           => 'Indonesia',
                'city'              => 'West Jakarta',
                'logo'              => 'binus_school.jpg',
                'cover_image'       => 'binus_school.jpg',
            ],
            [
                'company_id'        => 'C011',
                'page_id'           => 'EDU',
                'name'              => 'Harvard University',
                'industry'          => 'Higher Education',
                'tagline'           => 'Pursuing truth. Shaping the future',
                'established_date'  => '1636-10-28',
                'country'           => 'United States',
                'city'              => 'Cambridge',
                'logo'              => 'harvard.jpg',
                'cover_image'       => 'harvard.jpg',
            ],
            [
                'company_id'        => 'C012',
                'page_id'           => 'COM',
                'name'              => 'Ubisoft',
                'industry'          => 'Computer Games',
                'tagline'           => 'Creating worlds of fun and adventure',
                'established_date'  => '1986-03-28',
                'country'           => 'France',
                'city'              => 'Saint Mande',
                'logo'              => 'ubisoft.jpg',
                'cover_image'       => 'ubisoft.jpg',
            ],
            [
                'company_id'        => 'C013',
                'page_id'           => 'COM',
                'name'              => 'Bank Central Asia',
                'industry'          => 'Banking',
                'tagline'           => 'Trusted partner for your financial journey',
                'established_date'  => '1957-02-21',
                'country'           => 'Indonesia',
                'city'              => 'Central Jakarta',
                'logo'              => 'bca.jpg',
                'cover_image'       => 'bca.jpg',
            ],
        ]);
    }
}
