<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'user_id'       => 'U001',
                'name'          => 'Mohammad Rizqy Akmaluddin',
                'phone_number'  => '081908196194',
                'gender'        => 'Male',
                'dob'           => '2000-08-29',
                'country'       => 'Indonesia',
                'city'          => 'Jakarta Metropolitan Area',
                'email'         => 'mohammad.rizqy@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at BINUS University | Web Developer (PHP & React) | Freelance UI/UX Graphic Designer | Interest In Artificial Intelligence',
                'profile_image' => 'kicul.jpg',
                'cover_image'   => 'basic_cover1.jpg',
            ],
            [
                'user_id'       => 'U002',
                'name'          => 'Elizabeth Laura Helvin',
                'phone_number'  => '087498271672',
                'gender'        => 'Female',
                'dob'           => '2000-06-05',
                'country'       => 'Indonesia',
                'city'          => 'Tangerang',
                'email'         => 'elizabeth.laura@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Bina Nusantara University || Computer Science Undergraduate Student',
                'profile_image' => 'laura.jpg',
                'cover_image'   => 'laura.jpg',
            ],
            [
                'user_id'       => 'U003',
                'name'          => 'Prabowo Subianto',
                'phone_number'  => '08288849758',
                'gender'        => 'Male',
                'dob'           => '2000-10-17',
                'country'       => 'Indonesia',
                'city'          => 'Jakarta Metropolitan Area',
                'email'         => 'prabowo.subianto@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'MP for Richmond and Northallerton. Former Prime Minister of the United Kingdom. Promoted by Sam Gibbs at Omega Business Village, Northallerton DL6 2NJ.',
                'profile_image' => 'prabowo.jpg',
                'cover_image'   => 'basic_cover3.jpg',
            ],
            [
                'user_id'       => 'U004',
                'name'          => 'Joko Widodo',
                'phone_number'  => '08475628733',
                'gender'        => 'Male',
                'dob'           => '2000-06-21',
                'country'       => 'Indonesia',
                'city'          => 'Solo',
                'email'         => 'joko.widodo@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Former President of the Republic of Indonesia for 2 terms | Very handsome man from Solo',
                'profile_image' => 'jokowi.jpg',
                'cover_image'   => 'basic_cover4.jpg',
            ],
            [
                'user_id'       => 'U005',
                'name'          => 'Tom Cruise',
                'phone_number'  => '08746728364',
                'gender'        => 'Male',
                'dob'           => '2000-09-14',
                'country'       => 'United States',
                'city'          => 'New York',
                'email'         => 'tom.cruise@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Filmmaker | Director | Scriptwriter | Actor | Visual Storyteller | Creative Artist',
                'profile_image' => 'tom.jpg',
                'cover_image'   => 'basic_cover5.jpg',
            ],
            [
                'user_id'       => 'U006',
                'name'          => 'Alber Einstein',
                'phone_number'  => '084827737',
                'gender'        => 'Male',
                'dob'           => '2000-11-02',
                'country'       => 'United States',
                'city'          => 'Los Angeles',
                'email'         => 'albert.einstein@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'German-born theoretical physicist | scientist | philosopher of science| and world intellectual figure',
                'profile_image' => 'einstein.jpg',
                'cover_image'   => 'basic_cover6.jpg',
            ],
            [
                'user_id'       => 'U007',
                'name'          => 'Carlos Eduardo Silva',
                'phone_number'  => '081234567890',
                'gender'        => 'Male',
                'dob'           => '2000-03-12',
                'country'       => 'Brazil',
                'city'          => 'Rio de Janeiro',
                'email'         => 'carlos.eduardo@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Aspiring Data Analyst | Passionate about technology and innovation',
                'profile_image' => 'male23.jpg',
                'cover_image'   => 'basic_cover7.jpg',
            ],
            [
                'user_id'       => 'U008',
                'name'          => 'Aisha Noor Khan',
                'phone_number'  => '082345678901',
                'gender'        => 'Female',
                'dob'           => '2000-07-25',
                'country'       => 'Pakistan',
                'city'          => 'Lahore',
                'email'         => 'aisha.noor@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Marketing Specialist | Creative Thinker | Social Media Enthusiast',
                'profile_image' => 'female3.jpg',
                'cover_image'   => 'basic_cover8.jpg',
            ],
            [
                'user_id'       => 'U009',
                'name'          => 'Liam O Connor',
                'phone_number'  => '083456789012',
                'gender'        => 'Male',
                'dob'           => '2000-11-08',
                'country'       => 'Ireland',
                'city'          => 'Dublin',
                'email'         => 'liam.oconnor@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Software Engineer | Problem Solver | Team Player',
                'profile_image' => 'male7.jpg',
                'cover_image'   => 'basic_cover9.jpg',
            ],
            [
                'user_id'       => 'U010',
                'name'          => 'Sofia Rossi',
                'phone_number'  => '084567890123',
                'gender'        => 'Female',
                'dob'           => '2000-05-19',
                'country'       => 'Italy',
                'city'          => 'Milan',
                'email'         => 'sofia.rossi@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Business Development | Multilingual | Driven by results',
                'profile_image' => 'female21.jpg',
                'cover_image'   => 'basic_cover10.jpg',
            ],
            [
                'user_id'       => 'U011',
                'name'          => 'Yuki Tanaka',
                'phone_number'  => '085678901234',
                'gender'        => 'Female',
                'dob'           => '2000-02-28',
                'country'       => 'Japan',
                'city'          => 'Osaka',
                'email'         => 'yuki.tanaka@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'UI/UX Designer | Minimalist | Focused on user experience',
                'profile_image' => 'female8.jpg',
                'cover_image'   => 'basic_cover11.jpg',
            ],
            [
                'user_id'       => 'U012',
                'name'          => 'David Smith',
                'phone_number'  => '086789012345',
                'gender'        => 'Male',
                'dob'           => '2000-09-03',
                'country'       => 'United Kingdom',
                'city'          => 'Manchester',
                'email'         => 'david.smith@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Finance Graduate | Analytical Thinker | Eager to learn',
                'profile_image' => 'male2.jpg',
                'cover_image'   => 'basic_cover12.jpg',
            ],
            [
                'user_id'       => 'U013',
                'name'          => 'Fatima Zahra',
                'phone_number'  => '087890123456',
                'gender'        => 'Female',
                'dob'           => '2000-12-14',
                'country'       => 'Morocco',
                'city'          => 'Casablanca',
                'email'         => 'fatima.zahra@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Content Writer | Storyteller | Creative Mind',
                'profile_image' => 'female14.jpg',
                'cover_image'   => 'basic_cover1.jpg',
            ],
            [
                'user_id'       => 'U014',
                'name'          => 'Ivan Petrov',
                'phone_number'  => '088901234567',
                'gender'        => 'Male',
                'dob'           => '2000-06-21',
                'country'       => 'Russia',
                'city'          => 'Saint Petersburg',
                'email'         => 'ivan.petrov@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Network Engineer | Security Enthusiast | Lifelong Learner',
                'profile_image' => 'male18.jpg',
                'cover_image'   => 'basic_cover2.jpg',
            ],
            [
                'user_id'       => 'U015',
                'name'          => 'Linda Chen',
                'phone_number'  => '089012345678',
                'gender'        => 'Female',
                'dob'           => '2000-04-17',
                'country'       => 'China',
                'city'          => 'Shanghai',
                'email'         => 'linda.chen@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Project Manager | Agile Practitioner | Team Leader',
                'profile_image' => 'female19.jpg',
                'cover_image'   => 'basic_cover3.jpg',
            ],
            [
                'user_id'       => 'U016',
                'name'          => 'Samuel Johnson',
                'phone_number'  => '080123456789',
                'gender'        => 'Male',
                'dob'           => '2000-10-30',
                'country'       => 'United States',
                'city'          => 'Chicago',
                'email'         => 'samuel.johnson@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Entrepreneur | Startup Enthusiast | Growth Hacker',
                'profile_image' => 'male31.jpg',
                'cover_image'   => 'basic_cover4.jpg',
            ],
            [
                'user_id'       => 'U017',
                'name'          => 'Mateo Fernandez Ruiz',
                'phone_number'  => '081234567891',
                'gender'        => 'Male',
                'dob'           => '2000-01-15',
                'country'       => 'Spain',
                'city'          => 'Madrid',
                'email'         => 'mateo.fernandez@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Full Stack Developer specializing in cloud solutions and scalable web applications with a passion for open source technologies',
                'profile_image' => 'male9.jpg',
                'cover_image'   => 'basic_cover5.jpg',
            ],
            [
                'user_id'       => 'U018',
                'name'          => 'Amelia Nguyen Tran',
                'phone_number'  => '082345678912',
                'gender'        => 'Female',
                'dob'           => '2000-02-22',
                'country'       => 'Vietnam',
                'city'          => 'Ho Chi Minh',
                'email'         => 'amelia.nguyen@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Senior Frontend Engineer focused on React and TypeScript, experienced in building user-centric platforms for global audiences',
                'profile_image' => 'female6.jpg',
                'cover_image'   => 'basic_cover6.jpg',
            ],
            [
                'user_id'       => 'U019',
                'name'          => 'Lucas Martins Oliveira',
                'phone_number'  => '083456789123',
                'gender'        => 'Male',
                'dob'           => '2000-03-30',
                'country'       => 'Brazil',
                'city'          => 'Sao Paulo',
                'email'         => 'lucas.martins@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'DevOps Specialist with expertise in CI/CD pipelines, container orchestration, and cloud infrastructure automation',
                'profile_image' => 'male27.jpg',
                'cover_image'   => 'basic_cover7.jpg',
            ],
            [
                'user_id'       => 'U020',
                'name'          => 'Priya Sharma Patel',
                'phone_number'  => '084567891234',
                'gender'        => 'Female',
                'dob'           => '2000-04-05',
                'country'       => 'India',
                'city'          => 'Bangalore',
                'email'         => 'priya.sharma@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Data Scientist skilled in machine learning, big data analytics, and predictive modeling for enterprise solutions',
                'profile_image' => 'female11.jpg',
                'cover_image'   => 'basic_cover8.jpg',
            ],
            [
                'user_id'       => 'U021',
                'name'          => 'William Anderson Lee',
                'phone_number'  => '085678912345',
                'gender'        => 'Male',
                'dob'           => '2000-05-12',
                'country'       => 'Australia',
                'city'          => 'Sydney',
                'email'         => 'william.anderson@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Backend Engineer with strong experience in microservices architecture, API development, and distributed systems',
                'profile_image' => 'male21.jpg',
                'cover_image'   => 'basic_cover9.jpg',
            ],
            [
                'user_id'       => 'U022',
                'name'          => 'Sara Müller Schmidt',
                'phone_number'  => '086789123456',
                'gender'        => 'Female',
                'dob'           => '2000-06-18',
                'country'       => 'Germany',
                'city'          => 'Berlin',
                'email'         => 'sara.muller@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Cybersecurity Analyst focused on threat detection, vulnerability assessment, and network security for fintech companies',
                'profile_image' => 'female23.jpg',
                'cover_image'   => 'basic_cover10.jpg',
            ],
            [
                'user_id'       => 'U023',
                'name'          => 'Ahmed Hassan Ali',
                'phone_number'  => '087891234567',
                'gender'        => 'Male',
                'dob'           => '2000-07-24',
                'country'       => 'Egypt',
                'city'          => 'Cairo',
                'email'         => 'ahmed.hassan@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Mobile Application Developer with a background in cross-platform frameworks and UI/UX optimization for high-traffic apps',
                'profile_image' => 'male5.jpg',
                'cover_image'   => 'basic_cover11.jpg',
            ],
            [
                'user_id'       => 'U024',
                'name'          => 'Chloe Dubois Laurent',
                'phone_number'  => '088912345678',
                'gender'        => 'Female',
                'dob'           => '2000-08-29',
                'country'       => 'France',
                'city'          => 'Lyon',
                'email'         => 'chloe.dubois@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Cloud Solutions Architect specializing in AWS and Azure, passionate about designing scalable enterprise infrastructures',
                'profile_image' => 'female2.jpg',
                'cover_image'   => 'basic_cover12.jpg',
            ],
            [
                'user_id'       => 'U025',
                'name'          => 'Ivan Novak Markovic',
                'phone_number'  => '089123456789',
                'gender'        => 'Male',
                'dob'           => '2000-09-06',
                'country'       => 'Croatia',
                'city'          => 'Zagreb',
                'email'         => 'ivan.novak@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'IT Consultant with experience in digital transformation, business process automation, and ERP implementation',
                'profile_image' => 'male15.jpg',
                'cover_image'   => 'basic_cover12',
            ],
            [
                'user_id'       => 'U026',
                'name'          => 'Jasmine Lee Park',
                'phone_number'  => '080234567891',
                'gender'        => 'Female',
                'dob'           => '2000-10-13',
                'country'       => 'South Korea',
                'city'          => 'Seoul',
                'email'         => 'jasmine.lee@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Software QA Engineer dedicated to automated testing, continuous integration, and quality assurance for SaaS products',
                'profile_image' => 'female13.jpg',
                'cover_image'   => 'basic_cover11.jpg',
            ],
            [
                'user_id'       => 'U027',
                'name'          => 'Mohamed Abdulla Al Farsi',
                'phone_number'  => '081345678912',
                'gender'        => 'Male',
                'dob'           => '2000-11-20',
                'country'       => 'United Arab Emirates',
                'city'          => 'Dubai',
                'email'         => 'mohamed.abdulla@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Network Administrator with hands-on experience in enterprise networking, cloud migration, and IT support',
                'profile_image' => 'male34.jpg',
                'cover_image'   => 'basic_cover10.jpg',
            ],
            [
                'user_id'       => 'U028',
                'name'          => 'Sophia Russo Bianchi',
                'phone_number'  => '082456789123',
                'gender'        => 'Female',
                'dob'           => '2000-12-27',
                'country'       => 'Italy',
                'city'          => 'Rome',
                'email'         => 'sophia.russo@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Business Intelligence Analyst skilled in dashboard development, data visualization, and reporting for retail analytics',
                'profile_image' => 'female9.jpg',
                'cover_image'   => 'basic_cover9.jpg',
            ],
            [
                'user_id'       => 'U029',
                'name'          => 'Rafael Kimura',
                'phone_number'  => '081567891234',
                'gender'        => 'Male',
                'dob'           => '2000-01-22',
                'country'       => 'Indonesia',
                'city'          => 'Tangerang, Banten',
                'email'         => 'rafael.kimura@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Undergraduate Computer Science student at Binus University specializing in backend development and cloud infrastructure, passionate about scalable systems and automation',
                'profile_image' => 'male19.jpg',
                'cover_image'   => 'basic_cover8.jpg',
            ],
            [
                'user_id'       => 'U030',
                'name'          => 'Maria Fernanda Lopez',
                'phone_number'  => '082678912345',
                'gender'        => 'Female',
                'dob'           => '2000-02-14',
                'country'       => 'Indonesia',
                'city'          => 'Manado',
                'email'         => 'maria.fernanda@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at Binus University with strong interest in data science, machine learning, and building predictive models for real-world applications',
                'profile_image' => 'female10.jpg',
                'cover_image'   => 'basic_cover10.jpg',
            ],
            [
                'user_id'       => 'U031',
                'name'          => 'Samuel Adeyemi',
                'phone_number'  => '083789123456',
                'gender'        => 'Male',
                'dob'           => '2000-03-08',
                'country'       => 'Indonesia',
                'city'          => 'Central Jakarta',
                'email'         => 'samuel.adeyemi@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Undergraduate Computer Science student at Binus University focused on mobile application development, UI/UX design, and cross-platform frameworks',
                'profile_image' => 'male6.jpg',
                'cover_image'   => 'basic_cover7.jpg',
            ],
            [
                'user_id'       => 'U032',
                'name'          => 'Anna Petrova',
                'phone_number'  => '084891234567',
                'gender'        => 'Female',
                'dob'           => '2000-04-19',
                'country'       => 'Indonesia',
                'city'          => 'Central Jakarta',
                'email'         => 'anna.petrova@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at Binus University with expertise in web development, JavaScript frameworks, and responsive design for modern web applications',
                'profile_image' => 'female15.jpg',
                'cover_image'   => 'basic_cover9.jpg',
            ],
            [
                'user_id'       => 'U033',
                'name'          => 'Lucas Wang',
                'phone_number'  => '085912345678',
                'gender'        => 'Male',
                'dob'           => '2000-05-27',
                'country'       => 'Indonesia',
                'city'          => 'Central Jakarta',
                'email'         => 'lucas.wang@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Undergraduate Computer Science student at Binus University interested in cybersecurity, ethical hacking, and network security for enterprise environments',
                'profile_image' => 'male1.jpg',
                'cover_image'   => 'basic_cover12',
            ],
            [
                'user_id'       => 'U034',
                'name'          => 'Fatima El Amrani',
                'phone_number'  => '086123456789',
                'gender'        => 'Female',
                'dob'           => '2000-06-11',
                'country'       => 'Indonesia',
                'city'          => 'West Jakarta',
                'email'         => 'fatima.elamrani@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at Binus University passionate about artificial intelligence, natural language processing, and building intelligent chatbots',
                'profile_image' => 'female7.jpg',
                'cover_image'   => 'basic_cover10.jpg',
            ],
            [
                'user_id'       => 'U035',
                'name'          => 'David Müller',
                'phone_number'  => '087234567891',
                'gender'        => 'Male',
                'dob'           => '2000-07-03',
                'country'       => 'Indonesia',
                'city'          => 'Bekasi',
                'email'         => 'david.muller@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Undergraduate Computer Science student at Binus University with a focus on DevOps, CI/CD pipelines, and cloud-native application deployment',
                'profile_image' => 'male10.jpg',
                'cover_image'   => 'basic_cover11.jpg',
            ],
            [
                'user_id'       => 'U036',
                'name'          => 'Sara Oliveira',
                'phone_number'  => '088345678912',
                'gender'        => 'Female',
                'dob'           => '2000-08-15',
                'country'       => 'Indonesia',
                'city'          => 'Bekasi',
                'email'         => 'sara.oliveira@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at Binus University specializing in frontend engineering, React development, and user experience optimization',
                'profile_image' => 'female8.jpg',
                'cover_image'   => 'basic_cover8.jpg',
            ],
            [
                'user_id'       => 'U037',
                'name'          => 'William Anderson',
                'phone_number'  => '089456789123',
                'gender'        => 'Male',
                'dob'           => '2000-09-29',
                'country'       => 'Indonesia',
                'city'          => 'Depok',
                'email'         => 'william.anderson@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Undergraduate Computer Science student at Binus University with skills in API development, microservices architecture, and distributed systems',
                'profile_image' => 'male32.jpg',
                'cover_image'   => 'basic_cover9.jpg',
            ],
            [
                'user_id'       => 'U038',
                'name'          => 'Aisha Khan',
                'phone_number'  => '080567891234',
                'gender'        => 'Female',
                'dob'           => '2000-10-21',
                'country'       => 'Indonesia',
                'city'          => 'Semarang',
                'email'         => 'aisha.khan@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at Binus University interested in database management, SQL optimization, and backend engineering for scalable platforms',
                'profile_image' => 'female5.jpg',
                'cover_image'   => 'basic_cover6.jpg',
            ],
            [
                'user_id'       => 'U039',
                'name'          => 'Mateo Garcia',
                'phone_number'  => '081678912345',
                'gender'        => 'Male',
                'dob'           => '2000-11-12',
                'country'       => 'Indonesia',
                'city'          => 'Bandung',
                'email'         => 'mateo.garcia@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Undergraduate Computer Science student at Binus University | focused on cloud computing, serverless architectures, and automation with Python',
                'profile_image' => 'male13.jpg',
                'cover_image'   => 'basic_cover7.jpg',
            ],
            [
                'user_id'       => 'U040',
                'name'          => 'Chloe Laurent',
                'phone_number'  => '082789123456',
                'gender'        => 'Female',
                'dob'           => '2000-12-04',
                'country'       => 'Indonesia',
                'city'          => 'Jakarta Metropolitan Area',
                'email'         => 'chloe.laurent@gmail.com',
                'password'      => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline'      => 'Computer Science Student at Binus University | with a passion for machine learning, data visualization, and building interactive dashboards',
                'profile_image' => 'female10.jpg',
                'cover_image'   => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U041',
                'name' => 'Rizky Pratama',
                'phone_number' => '081234567891',
                'gender' => 'Male',
                'dob' => '2000-01-10',
                'country' => 'Indonesia',
                'city' => 'Bandung',
                'email' => 'rizky.pratama@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Computer Science Student at Binus University focusing on mobile app development and Flutter framework for scalable solutions',
                'profile_image' => 'male3.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U042',
                'name' => 'Dewi Lestari',
                'phone_number' => '082345678912',
                'gender' => 'Female',
                'dob' => '2000-02-18',
                'country' => 'Indonesia',
                'city' => 'Surabaya',
                'email' => 'dewi.lestari@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Web developer and UI designer at Binus University | Passionate about creating intuitive user interfaces and seamless user experiences',
                'profile_image' => 'female12.jpg',
                'cover_image' => 'basic_cover7.jpg',
            ],
            [
                'user_id' => 'U043',
                'name' => 'Aditya Nugroho',
                'phone_number' => '083456789123',
                'gender' => 'Male',
                'dob' => '2000-03-25',
                'country' => 'Indonesia',
                'city' => 'Yogyakarta',
                'email' => 'aditya.nugroho@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Backend Engineer | Expertise in Node.js and RESTful API development, currently studying Computer Science at Binus University',
                'profile_image' => 'male25.jpg',
                'cover_image' => 'basic_cover6.jpg',
            ],
            [
                'user_id' => 'U044',
                'name' => 'Putri Maharani',
                'phone_number' => '084567891234',
                'gender' => 'Female',
                'dob' => '2000-04-30',
                'country' => 'Indonesia',
                'city' => 'Semarang',
                'email' => 'putri.maharani@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Machine Learning enthusiast | Data Analyst | Skilled in Python and R | active in Binus University research projects',
                'profile_image' => 'female18.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U045',
                'name' => 'Fajar Santoso',
                'phone_number' => '085678912345',
                'gender' => 'Male',
                'dob' => '2000-05-12',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'email' => 'fajar.santoso@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Full stack web developer with a focus on React and Laravel | Passionate about building scalable web platforms',
                'profile_image' => 'male20.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U046',
                'name' => 'Siti Rahmawati',
                'phone_number' => '086789123456',
                'gender' => 'Female',
                'dob' => '2000-06-21',
                'country' => 'Indonesia',
                'city' => 'Malang',
                'email' => 'siti.rahmawati@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Cybersecurity enthusiast and ethical hacker, interested in penetration testing and network security, Binus University student',
                'profile_image' => 'female4.jpg',
                'cover_image' => 'basic_cover12.jpg',
            ],
            [
                'user_id' => 'U047',
                'name' => 'Bayu Saputra',
                'phone_number' => '087891234567',
                'gender' => 'Male',
                'dob' => '2000-07-14',
                'country' => 'Indonesia',
                'city' => 'Denpasar',
                'email' => 'bayu.saputra@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'DevOps practitioner with skills in Docker, Kubernetes, and CI/CD pipelines, currently learning cloud infrastructure at Binus University',
                'profile_image' => 'male22.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U048',
                'name' => 'Melati Anggraini',
                'phone_number' => '088912345678',
                'gender' => 'Female',
                'dob' => '2000-08-27',
                'country' => 'Indonesia',
                'city' => 'Makassar',
                'email' => 'melati.anggraini@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Frontend developer specializing in Vue.js and responsive design, passionate about accessibility and user-centric web applications',
                'profile_image' => 'female16.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U049',
                'name' => 'Dimas Wijaya',
                'phone_number' => '089123456789',
                'gender' => 'Male',
                'dob' => '2000-09-05',
                'country' => 'Indonesia',
                'city' => 'Palembang',
                'email' => 'dimas.wijaya@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Database administrator with experience in MySQL and PostgreSQL, interested in data warehousing and analytics',
                'profile_image' => 'male24.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U050',
                'name' => 'Intan Permatasari',
                'phone_number' => '080234567891',
                'gender' => 'Female',
                'dob' => '2000-10-16',
                'country' => 'Indonesia',
                'city' => 'Bogor',
                'email' => 'intan.permatasari@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Software tester and QA engineer, skilled in automated testing and bug tracking, active in Binus University tech community',
                'profile_image' => 'female1.jpg',
                'cover_image' => 'basic_cover11.jpg',
            ],
            [
                'user_id' => 'U051',
                'name' => 'Victor Ivanov',
                'phone_number' => '081345678901',
                'gender' => 'Male',
                'dob' => '2000-01-28',
                'country' => 'Russia',
                'city' => 'Moscow',
                'email' => 'victor.ivanov@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Cloud Infrastructure Specialist with expertise in AWS, Azure, and Google Cloud, focusing on enterprise migration and automation',
                'profile_image' => 'male26.jpg',
                'cover_image' => 'basic_cover6.jpg',
            ],
            [
                'user_id' => 'U052',
                'name' => 'Sophia Martinez',
                'phone_number' => '082456789012',
                'gender' => 'Female',
                'dob' => '2000-02-15',
                'country' => 'Spain',
                'city' => 'Barcelona',
                'email' => 'sophia.martinez@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Cybersecurity Specialist experienced in penetration testing, vulnerability assessment, and security architecture for financial institutions',
                'profile_image' => 'female14.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U053',
                'name' => 'John Miller',
                'phone_number' => '083567890123',
                'gender' => 'Male',
                'dob' => '2000-03-22',
                'country' => 'United States',
                'city' => 'San Francisco',
                'email' => 'john.miller@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'DevOps Engineer specializing in CI/CD, container orchestration with Kubernetes, and infrastructure as code',
                'profile_image' => 'male8.jpg',
                'cover_image' => 'basic_cover7.jpg',
            ],
            [
                'user_id' => 'U054',
                'name' => 'Amina Hassan',
                'phone_number' => '084678901234',
                'gender' => 'Female',
                'dob' => '2000-04-09',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'email' => 'amina.hassan@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Data Science Specialist with a focus on big data analytics, machine learning, and predictive modeling for healthcare',
                'profile_image' => 'female22.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U055',
                'name' => 'Luca Romano',
                'phone_number' => '085789012345',
                'gender' => 'Male',
                'dob' => '2000-05-17',
                'country' => 'Italy',
                'city' => 'Rome',
                'email' => 'luca.romano@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Software Architect with experience in designing scalable microservices, distributed systems, and enterprise solutions',
                'profile_image' => 'male4.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U056',
                'name' => 'Emily Clark',
                'phone_number' => '086890123456',
                'gender' => 'Female',
                'dob' => '2000-06-24',
                'country' => 'United Kingdom',
                'city' => 'London',
                'email' => 'emily.clark@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'IT Security Specialist focused on network security, incident response, and compliance for multinational corporations',
                'profile_image' => 'female20.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U057',
                'name' => 'Mohammed Al Saeed',
                'phone_number' => '087901234567',
                'gender' => 'Male',
                'dob' => '2000-07-31',
                'country' => 'Saudi Arabia',
                'city' => 'Riyadh',
                'email' => 'mohammed.alsaeed@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Mobile Application Specialist skilled in Android and iOS development, cross-platform frameworks, and UI/UX optimization',
                'profile_image' => 'male30.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U058',
                'name' => 'Julie Tremblay',
                'phone_number' => '088012345678',
                'gender' => 'Female',
                'dob' => '2000-08-18',
                'country' => 'Canada',
                'city' => 'Montreal',
                'email' => 'julie.tremblay@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Business Intelligence Specialist with expertise in dashboard development, data visualization, and analytics for retail',
                'profile_image' => 'female3.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U059',
                'name' => 'Hans Schneider',
                'phone_number' => '089123456789',
                'gender' => 'Male',
                'dob' => '2000-09-26',
                'country' => 'Germany',
                'city' => 'Frankfurt',
                'email' => 'hans.schneider@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Network Specialist experienced in enterprise networking, cloud migration, and IT infrastructure management',
                'profile_image' => 'male11.jpg',
                'cover_image' => 'basic_cover12',
            ],
            [
                'user_id' => 'U060',
                'name' => 'Yuna Kim',
                'phone_number' => '080234567891',
                'gender' => 'Female',
                'dob' => '2000-10-13',
                'country' => 'South Korea',
                'city' => 'Seoul',
                'email' => 'yuna.kim@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'AI Specialist focused on deep learning | Computer Vision | natural language processing for innovative tech solutions',
                'profile_image' => 'female24.jpg',
                'cover_image' => 'basic_cover11.jpg',
            ],
            [
                'user_id' => 'U061',
                'name' => 'Bill Gates',
                'phone_number' => '08274937822',
                'gender' => 'Male',
                'dob' => '2000-10-28',
                'country' => 'United States',
                'city' => 'Seattle',
                'email' => 'bill.gates@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Co-founder of Microsoft | philanthropist | technology visionary known for revolutionizing personal computing',
                'profile_image' => 'bill.jpg',
                'cover_image' => 'basic_cover7.jpg',
            ],
            [
                'user_id' => 'U062',
                'name' => 'Steve Jobs',
                'phone_number' => '084799993383',
                'gender' => 'Male',
                'dob' => '2000-02-24',
                'country' => 'United States',
                'city' => 'San Francisco',
                'email' => 'steve.jobs@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Co-founder of Apple | pioneer in consumer electronics, design, and digital innovation',
                'profile_image' => 'steve.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U063',
                'name' => 'Mark Zuckerberg',
                'phone_number' => '084777892664',
                'gender' => 'Male',
                'dob' => '2000-05-14',
                'country' => 'United States',
                'city' => 'Palo Alto',
                'email' => 'mark.zuckerberg@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Co-founder and CEO of Facebook | leading social media innovation and global connectivity',
                'profile_image' => 'mark.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U064',
                'name' => 'Jeff Bezos',
                'phone_number' => '084777728993',
                'gender' => 'Male',
                'dob' => '2000-01-12',
                'country' => 'United States',
                'city' => 'Seattle',
                'email' => 'jeff.bezos@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Founder of Amazon | e-commerce and cloud computing leader | entrepreneur and investor',
                'profile_image' => 'jeff.jpg',
                'cover_image' => 'basic_cover6.jpg',
            ],
            [
                'user_id' => 'U065',
                'name' => 'Larry Page',
                'phone_number' => '083889937488',
                'gender' => 'Male',
                'dob' => '2000-03-26',
                'country' => 'United States',
                'city' => 'Mountain View',
                'email' => 'larry.page@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Co-founder of Google | Computer Scientist and advocate for technological advancement',
                'profile_image' => 'male16.jpg',
                'cover_image' => 'basic_cover12',
            ],
            [
                'user_id' => 'U066',
                'name' => 'Sergey Brin',
                'phone_number' => '08478927487',
                'gender' => 'Male',
                'dob' => '2000-08-21',
                'country' => 'United States',
                'city' => 'Mountain View',
                'email' => 'sergey.brin@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Co-founder of Google, innovator in search engine technology and artificial intelligence',
                'profile_image' => 'male14.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U067',
                'name' => 'Zhang Yiming',
                'phone_number' => '084793777294',
                'gender' => 'Male',
                'dob' => '2000-04-01',
                'country' => 'China',
                'city' => 'Beijing',
                'email' => 'zhang.yiming@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Founder of ByteDance, creator of TikTok, driving global short video and content platforms',
                'profile_image' => 'male28.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U068',
                'name' => 'William Tanuwijaya',
                'phone_number' => '084777493833',
                'gender' => 'Male',
                'dob' => '2000-11-11',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'email' => 'william.tanuwijaya@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Co-founder and CEO of Tokopedia, leading Indonesia’s digital marketplace transformation',
                'profile_image' => 'william.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U069',
                'name' => 'Jack Ma',
                'phone_number' => '081282929988',
                'gender' => 'Male',
                'dob' => '2000-09-10',
                'country' => 'China',
                'city' => 'Hangzhou',
                'email' => 'jack.ma@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Founder of Alibaba Group, entrepreneur and advocate for digital economy and e-commerce',
                'profile_image' => 'jackma.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U070',
                'name' => 'Tim Cook',
                'phone_number' => '08477883774',
                'gender' => 'Male',
                'dob' => '2000-11-01',
                'country' => 'United States',
                'city' => 'Cupertino',
                'email' => 'tim.cook@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'CEO of Apple | driving innovation in consumer technology and global supply chain management',
                'profile_image' => 'tim.jpg',
                'cover_image' => 'basic_cover11.jpg',
            ],
            [
                'user_id' => 'U071',
                'name' => 'Andi Wijaya',
                'phone_number' => '081234567890',
                'gender' => 'Male',
                'dob' => '2000-07-15',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'email' => 'andi.wijaya@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Senior Software Engineer at Tokopedia | Passionate about teaching computer science and developing scalable e-commerce platforms | Experienced in cloud architecture and agile methodologies',
                'profile_image' => 'male29.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U072',
                'name' => 'Siti Nurhaliza',
                'phone_number' => '082345678900',
                'gender' => 'Female',
                'dob' => '2000-03-21',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'email' => 'siti.nurhaliza@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Lead Data Scientist at Gojek | Dedicated to advancing data-driven decision making in academia and industry | Experienced in big data analytics and machine learning deployment',
                'profile_image' => 'female2.jpg',
                'cover_image' => 'basic_cover7.jpg',
            ],
            [
                'user_id' => 'U073',
                'name' => 'Budi Santoso',
                'phone_number' => '083456789011',
                'gender' => 'Male',
                'dob' => '2000-06-12',
                'country' => 'Indonesia',
                'city' => 'Bandung',
                'email' => 'budi.santoso@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Senior Lecturer at Binus University | Principal Software Architect at Bukalapak | Focused on scalable system design and mentoring future tech leaders | Expert in microservices and cloud-native applications',
                'profile_image' => 'male17.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U074',
                'name' => 'Dewi Anggraini',
                'phone_number' => '084567890122',
                'gender' => 'Female',
                'dob' => '2000-09-05',
                'country' => 'Indonesia',
                'city' => 'Surabaya',
                'email' => 'dewi.anggraini@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Computer Science Lecturer at Binus University | Product Manager at Tokopedia | Passionate about bridging academic research and real-world product innovation | Skilled in agile methodologies and user experience design',
                'profile_image' => 'female6.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U075',
                'name' => 'Rizky Ramadhan',
                'phone_number' => '085678901233',
                'gender' => 'Male',
                'dob' => '2000-12-18',
                'country' => 'Indonesia',
                'city' => 'Yogyakarta',
                'email' => 'rizky.ramadhan@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Senior Backend Developer at Traveloka | Specializing in distributed systems and API development | Committed to fostering collaboration between education and industry',
                'profile_image' => 'male35.jpg',
                'cover_image' => 'basic_cover6.jpg',
            ],
            [
                'user_id' => 'U076',
                'name' => 'Melati Prameswari',
                'phone_number' => '086789012344',
                'gender' => 'Female',
                'dob' => '2000-05-27',
                'country' => 'Indonesia',
                'city' => 'Medan',
                'email' => 'melati.prameswari@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Data Engineer at Tokopedia | Experienced in ETL pipeline development and cloud data warehousing | Advocates for practical learning and industry partnerships',
                'profile_image' => 'female19.jpg',
                'cover_image' => 'basic_cover12',
            ],
            [
                'user_id' => 'U077',
                'name' => 'Agus Wijaya',
                'phone_number' => '087890123455',
                'gender' => 'Male',
                'dob' => '2000-08-09',
                'country' => 'Indonesia',
                'city' => 'Semarang',
                'email' => 'agus.wijaya@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Senior Lecturer at Binus University | DevOps Lead at Bukalapak | Focused on automation, CI/CD, and infrastructure as code | Passionate about integrating modern practices into academic curriculum',
                'profile_image' => 'male33.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U078',
                'name' => 'Intan Permata',
                'phone_number' => '088901234566',
                'gender' => 'Female',
                'dob' => '2000-11-30',
                'country' => 'Indonesia',
                'city' => 'Makassar',
                'email' => 'intan.permata@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Frontend Engineer at Gojek | Specializing in modern JavaScript frameworks and responsive design | Dedicated to empowering students with industry-relevant skills',
                'profile_image' => 'female17.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U079',
                'name' => 'Fajar Hidayat',
                'phone_number' => '089012345677',
                'gender' => 'Male',
                'dob' => '2000-02-14',
                'country' => 'Indonesia',
                'city' => 'Palembang',
                'email' => 'fajar.hidayat@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Security Analyst at Tokopedia | Experienced in penetration testing and network security | Committed to advancing cybersecurity education and awareness',
                'profile_image' => 'male34.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U080',
                'name' => 'Putri Maharani',
                'phone_number' => '080123456788',
                'gender' => 'Female',
                'dob' => '2000-04-22',
                'country' => 'Indonesia',
                'city' => 'Denpasar',
                'email' => 'putri.maharani@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Lecturer at Binus University | Mobile Application Developer at Traveloka | Skilled in cross-platform development and UI/UX optimization | Advocates for hands-on learning and industry collaboration',
                'profile_image' => 'female8.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U081',
                'name' => 'Arif Setiawan',
                'phone_number' => '081234567891',
                'gender' => 'Male',
                'dob' => '2000-03-10',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'email' => 'arif.setiawan@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Experienced IT Consultant | Specializing in enterprise software solutions and digital transformation | Skilled in project management and system integration | Passionate about helping businesses leverage technology for growth',
                'profile_image' => 'male2.jpg',
                'cover_image' => 'basic_cover11.jpg',
            ],
            [
                'user_id' => 'U082',
                'name' => 'Maya Sari',
                'phone_number' => '082345678912',
                'gender' => 'Female',
                'dob' => '2000-07-22',
                'country' => 'Indonesia',
                'city' => 'Bandung',
                'email' => 'maya.sari@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Senior Software Engineer | Expert in backend development and cloud infrastructure | Extensive experience in building scalable applications for fintech and e-commerce | Advocate for clean code and agile practices',
                'profile_image' => 'female21.jpg',
                'cover_image' => 'basic_cover7.jpg',
            ],
            [
                'user_id' => 'U083',
                'name' => 'Dwi Prasetyo',
                'phone_number' => '083456789123',
                'gender' => 'Male',
                'dob' => '2000-11-05',
                'country' => 'Indonesia',
                'city' => 'Surabaya',
                'email' => 'dwi.prasetyo@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'IT Project Manager | Over 10 years managing large-scale software projects | Skilled in team leadership, agile methodologies, and stakeholder communication | Focused on delivering innovative tech solutions',
                'profile_image' => 'male7.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U084',
                'name' => 'Rina Kusuma',
                'phone_number' => '084567891234',
                'gender' => 'Female',
                'dob' => '2000-05-18',
                'country' => 'Indonesia',
                'city' => 'Yogyakarta',
                'email' => 'rina.kusuma@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Cybersecurity Specialist | Experienced in network security, penetration testing, and incident response | Passionate about educating organizations on digital safety | Contributor to national IT security forums',
                'profile_image' => 'female23.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U085',
                'name' => 'Faisal Akbar',
                'phone_number' => '085678912345',
                'gender' => 'Male',
                'dob' => '2000-09-27',
                'country' => 'Indonesia',
                'city' => 'Medan',
                'email' => 'faisal.akbar@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'DevOps Engineer | Skilled in automation, CI/CD pipelines, and cloud deployment | Extensive experience with Docker, Kubernetes, and AWS | Committed to optimizing development workflows',
                'profile_image' => 'male5.jpg',
                'cover_image' => 'basic_cover6.jpg',
            ],
            [
                'user_id' => 'U086',
                'name' => 'Siti Aminah',
                'phone_number' => '086789123456',
                'gender' => 'Female',
                'dob' => '2000-12-14',
                'country' => 'Indonesia',
                'city' => 'Makassar',
                'email' => 'siti.aminah@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Mobile Application Developer | Expert in Android and iOS platforms | Experienced in cross-platform development and UI/UX design | Focused on delivering high-quality user experiences',
                'profile_image' => 'female20.jpg',
                'cover_image' => 'basic_cover12',
            ],
            [
                'user_id' => 'U087',
                'name' => 'Bayu Nugroho',
                'phone_number' => '087891234567',
                'gender' => 'Male',
                'dob' => '2000-02-28',
                'country' => 'Indonesia',
                'city' => 'Semarang',
                'email' => 'bayu.nugroho@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Database Administrator | Specializing in MySQL, PostgreSQL, and data warehousing | Experienced in performance tuning and backup strategies | Passionate about data integrity and security',
                'profile_image' => 'male8.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U088',
                'name' => 'Intan Wulandari',
                'phone_number' => '088912345678',
                'gender' => 'Female',
                'dob' => '2000-06-09',
                'country' => 'Indonesia',
                'city' => 'Palembang',
                'email' => 'intan.wulandari@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Business Intelligence Analyst | Skilled in data visualization, dashboard creation, and analytics for retail and finance | Experienced in Power BI and Tableau | Advocate for data-driven decision making',
                'profile_image' => 'female15.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U089',
                'name' => 'Rizky Saputra',
                'phone_number' => '089123456789',
                'gender' => 'Male',
                'dob' => '2000-08-16',
                'country' => 'Indonesia',
                'city' => 'Bogor',
                'email' => 'rizky.saputra@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Network Engineer | Experienced in enterprise networking, cloud migration, and IT infrastructure management | Skilled in Cisco and Juniper technologies | Focused on reliable and secure connectivity',
                'profile_image' => 'male3.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U090',
                'name' => 'Melati Anggraeni',
                'phone_number' => '080234567891',
                'gender' => 'Female',
                'dob' => '2000-04-03',
                'country' => 'Indonesia',
                'city' => 'Denpasar',
                'email' => 'melati.anggraeni@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'AI Specialist | Experienced in machine learning, computer vision, and natural language processing | Skilled in Python and TensorFlow | Passionate about building intelligent solutions for real-world problems',
                'profile_image' => 'female18.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U091',
                'name' => 'Samuel Lee',
                'phone_number' => '081234567892',
                'gender' => 'Male',
                'dob' => '2000-05-21',
                'country' => 'Singapore',
                'city' => 'Singapore',
                'email' => 'samuel.lee@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Cloud Engineer | Specializing in AWS and GCP | Passionate about scalable infrastructure and automation',
                'profile_image' => 'male9.jpg',
                'cover_image' => 'basic_cover11.jpg',
            ],
            [
                'user_id' => 'U092',
                'name' => 'Olivia Brown',
                'phone_number' => '082345678913',
                'gender' => 'Female',
                'dob' => '2000-08-13',
                'country' => 'Australia',
                'city' => 'Melbourne',
                'email' => 'olivia.brown@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'UI Designer | Focused on mobile-first design and accessibility | Advocate for inclusive tech',
                'profile_image' => 'female4.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U093',
                'name' => 'Muhammad Fahri',
                'phone_number' => '083456789124',
                'gender' => 'Male',
                'dob' => '2000-11-02',
                'country' => 'Indonesia',
                'city' => 'Surabaya',
                'email' => 'muhammad.fahri@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Backend Developer | Skilled in Node.js and Python | Interested in distributed systems',
                'profile_image' => 'male6.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U094',
                'name' => 'Siti Zahra',
                'phone_number' => '084567891235',
                'gender' => 'Female',
                'dob' => '2000-03-29',
                'country' => 'Indonesia',
                'city' => 'Bandung',
                'email' => 'siti.zahra@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Frontend Developer | React & Vue.js | Passionate about user experience and design systems',
                'profile_image' => 'female12.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U095',
                'name' => 'Kevin Hartono',
                'phone_number' => '085678912346',
                'gender' => 'Male',
                'dob' => '2000-07-17',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'email' => 'kevin.hartono@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Mobile Developer | Flutter & Kotlin | Interested in cross-platform solutions',
                'profile_image' => 'male10.jpg',
                'cover_image' => 'basic_cover7.jpg',
            ],
            [
                'user_id' => 'U096',
                'name' => 'Amelia Putri',
                'phone_number' => '086789123457',
                'gender' => 'Female',
                'dob' => '2000-09-23',
                'country' => 'Indonesia',
                'city' => 'Yogyakarta',
                'email' => 'amelia.putri@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Data Analyst | Skilled in SQL and Tableau | Passionate about data-driven decisions',
                'profile_image' => 'female16.jpg',
                'cover_image' => 'basic_cover8.jpg',
            ],
            [
                'user_id' => 'U097',
                'name' => 'Rizal Hakim',
                'phone_number' => '087891234568',
                'gender' => 'Male',
                'dob' => '2000-12-05',
                'country' => 'Indonesia',
                'city' => 'Semarang',
                'email' => 'rizal.hakim@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'DevOps Engineer | Docker & Kubernetes | Focused on automation and CI/CD',
                'profile_image' => 'male12.jpg',
                'cover_image' => 'basic_cover9.jpg',
            ],
            [
                'user_id' => 'U098',
                'name' => 'Nadia Salsabila',
                'phone_number' => '088912345679',
                'gender' => 'Female',
                'dob' => '2000-04-14',
                'country' => 'Indonesia',
                'city' => 'Makassar',
                'email' => 'nadia.salsabila@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'QA Engineer | Automated Testing | Passionate about software quality',
                'profile_image' => 'female7.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U099',
                'name' => 'Dewi Kartika',
                'phone_number' => '089123456790',
                'gender' => 'Female',
                'dob' => '2000-06-28',
                'country' => 'Indonesia',
                'city' => 'Denpasar',
                'email' => 'dewi.kartika@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Business Analyst | Skilled in requirements gathering and process improvement',
                'profile_image' => 'female11.jpg',
                'cover_image' => 'basic_cover11.jpg',
            ],
            [
                'user_id' => 'U100',
                'name' => 'Andi Prasetya',
                'phone_number' => '080234567892',
                'gender' => 'Male',
                'dob' => '2000-10-09',
                'country' => 'Indonesia',
                'city' => 'Bogor',
                'email' => 'andi.prasetya@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Network Security Specialist | Experienced in firewalls and VPNs | Interested in cybersecurity research',
                'profile_image' => 'male18.jpg',
                'cover_image' => 'basic_cover12',
            ],
            [
                'user_id' => 'U101',
                'name' => 'Nadiem Makarim',
                'phone_number' => '083456789124',
                'gender' => 'Male',
                'dob' => '2000-12-24',
                'country' => 'Indonesia',
                'city' => 'West Jakarta',
                'email' => 'nadiem.makarim@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'Founder of Gojek Company | Entrepreneur and advocate | Marketing Specialist',
                'profile_image' => 'nadiem.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],
            [
                'user_id' => 'U102',
                'name' => 'Satya Nadella',
                'phone_number' => '083456789124',
                'gender' => 'Male',
                'dob' => '2000-12-24',
                'country' => 'United States',
                'city' => 'Washington DC',
                'email' => 'satya.nadella@gmail.com',
                'password' => '$2y$10$d4it.de0T9ma7loO434H4.QjPjsZ/ciF4tAt/i6llyQI5BHkAG0Ze',
                'headline' => 'CEO of Microsoft Cooperate | Entrepreneur and advocate | Marketing Specialist',
                'profile_image' => 'satya.jpg',
                'cover_image' => 'basic_cover10.jpg',
            ],

        ]);
    }
}
