<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserEducationSeeder extends Seeder
{
    public function run()
    {
        DB::table('user_educations')->insert([
            [
                'user_id'       => 'U001',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.25,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U001',
                'company_id'    => 'C009',
                'major_id'      => 1,
                'GPA'           => 3.70,
                'start_date'    => '2018-08-01',
                'end_date'      => null,
            ],

            // U002: Highschool → Diploma → Bachelor
            [
                'user_id'       => 'U002',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.41,
                'start_date'    => '2014-07-01',
                'end_date'      => '2017-05-01',
            ],
            [
                'user_id'       => 'U002',
                'company_id'    => 'C010',
                'major_id'      => 25,
                'GPA'           => 3.60,
                'start_date'    => '2017-09-01',
                'end_date'      => '2020-06-01',
            ],
            [
                'user_id'       => 'U002',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.78,
                'start_date'    => '2020-08-01',
                'end_date'      => '2024-06-01',
            ],

            // U003: Bachelor → Master
            [
                'user_id'       => 'U003',
                'company_id'    => 'C009',
                'major_id'      => 12,
                'GPA'           => 3.67,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U003',
                'company_id'    => 'C011',
                'major_id'      => 30,
                'GPA'           => 3.89,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U004: Bachelor → Master → Doctor
            [
                'user_id'       => 'U004',
                'company_id'    => 'C009',
                'major_id'      => 4,
                'GPA'           => 3.75,
                'start_date'    => '2014-08-01',
                'end_date'      => '2018-06-01',
            ],
            [
                'user_id'       => 'U004',
                'company_id'    => 'C011',
                'major_id'      => 35,
                'GPA'           => 3.88,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-06-01',
            ],
            [
                'user_id'       => 'U004',
                'company_id'    => 'C011',
                'major_id'      => 40,
                'GPA'           => 3.97,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],

            // U005: Bachelor → Master
            [
                'user_id'       => 'U005',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.74,
                'start_date'    => '2018-09-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U005',
                'company_id'    => 'C011',
                'major_id'      => 37,
                'GPA'           => 3.91,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U006: Highschool → Bachelor
            [
                'user_id'       => 'U006',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.32,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U006',
                'company_id'    => 'C009',
                'major_id'      => 11,
                'GPA'           => 3.70,
                'start_date'    => '2018-08-01',
                'end_date'      => null,
            ],

            // U007: Bachelor → Master → Doctor
            [
                'user_id'       => 'U007',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.78,
                'start_date'    => '2015-08-01',
                'end_date'      => '2019-06-01',
            ],
            [
                'user_id'       => 'U007',
                'company_id'    => 'C009',
                'major_id'      => 19,
                'GPA'           => 3.92,
                'start_date'    => '2019-08-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U007',
                'company_id'    => 'C011',
                'major_id'      => 43,
                'GPA'           => 3.98,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U008: Diploma → Bachelor
            [
                'user_id'       => 'U008',
                'company_id'    => 'C010',
                'major_id'      => 25,
                'GPA'           => 3.61,
                'start_date'    => '2016-09-01',
                'end_date'      => '2019-06-01',
            ],
            [
                'user_id'       => 'U008',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.79,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-06-01',
            ],

            // U009: Bachelor → Master
            [
                'user_id'       => 'U009',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.72,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U009',
                'company_id'    => 'C011',
                'major_id'      => 33,
                'GPA'           => 3.86,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U010: Bachelor → Master → Doctor
            [
                'user_id'       => 'U010',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.80,
                'start_date'    => '2016-08-01',
                'end_date'      => '2020-06-01',
            ],
            [
                'user_id'       => 'U010',
                'company_id'    => 'C009',
                'major_id'      => 20,
                'GPA'           => 3.90,
                'start_date'    => '2020-09-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U010',
                'company_id'    => 'C011',
                'major_id'      => 41,
                'GPA'           => 3.99,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],
            // Bachelor only
            [
                'user_id'       => 'U011',
                'company_id'    => 'C009',
                'major_id'      => 1,
                'GPA'           => 3.65,
                'start_date'    => '2019-08-01',
                'end_date'      => '2023-06-01',
            ],
            [
                'user_id'       => 'U012',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.72,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U013',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.80,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U014',
                'company_id'    => 'C009',
                'major_id'      => 4,
                'GPA'           => 3.56,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U015',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.68,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U016',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.74,
                'start_date'    => '2019-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U017',
                'company_id'    => 'C009',
                'major_id'      => 7,
                'GPA'           => 3.91,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U018',
                'company_id'    => 'C009',
                'major_id'      => 8,
                'GPA'           => 3.84,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U019',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.77,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U020',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.69,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-06-01',
            ],
            [
                'user_id'       => 'U021',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.85,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U022',
                'company_id'    => 'C009',
                'major_id'      => 11,
                'GPA'           => 3.59,
                'start_date'    => '2020-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U023',
                'company_id'    => 'C009',
                'major_id'      => 12,
                'GPA'           => 3.88,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U024',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.73,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-06-01',
            ],
            [
                'user_id'       => 'U025',
                'company_id'    => 'C009',
                'major_id'      => 13,
                'GPA'           => 3.95,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            // === U026 ===
            [
                'user_id'       => 'U026',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.20,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U026',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.74,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],

            // === U027 ===
            [
                'user_id'       => 'U027',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.31,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U027',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.78,
                'start_date'    => '2019-09-01',
                'end_date'      => null,
            ],

            // === U028 ===
            [
                'user_id'       => 'U028',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.45,
                'start_date'    => '2014-07-01',
                'end_date'      => '2017-05-01',
            ],
            [
                'user_id'       => 'U028',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.83,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],

            // === U029 ===
            [
                'user_id'       => 'U029',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.28,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U029',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.79,
                'start_date'    => '2018-09-01',
                'end_date'      => '2022-06-01',
            ],

            // === U030 ===
            [
                'user_id'       => 'U030',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.39,
                'start_date'    => '2014-07-01',
                'end_date'      => '2017-05-01',
            ],
            [
                'user_id'       => 'U030',
                'company_id'    => 'C009',
                'major_id'      => 7,
                'GPA'           => 3.70,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],

            // === U031 ===
            [
                'user_id'       => 'U031',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.22,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U031',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.85,
                'start_date'    => '2019-09-01',
                'end_date'      => null,
            ],

            // === U032 ===
            [
                'user_id'       => 'U032',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.40,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U032',
                'company_id'    => 'C009',
                'major_id'      => 12,
                'GPA'           => 3.68,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],

            // === U033 ===
            [
                'user_id'       => 'U033',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.36,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U033',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.82,
                'start_date'    => '2019-08-01',
                'end_date'      => '2023-06-01',
            ],

            // === U034 ===
            [
                'user_id'       => 'U034',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.30,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U034',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.79,
                'start_date'    => '2018-09-01',
                'end_date'      => '2022-06-01',
            ],

            // === U035 ===
            [
                'user_id'       => 'U035',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.48,
                'start_date'    => '2014-07-01',
                'end_date'      => '2017-05-01',
            ],
            [
                'user_id'       => 'U035',
                'company_id'    => 'C009',
                'major_id'      => 8,
                'GPA'           => 3.93,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-06-01',
            ],

            // === U036 ===
            [
                'user_id'       => 'U036',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.29,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U036',
                'company_id'    => 'C009',
                'major_id'      => 13,
                'GPA'           => 3.84,
                'start_date'    => '2018-08-01',
                'end_date'      => null,
            ],

            // === U037 ===
            [
                'user_id'       => 'U037',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.21,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U037',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.75,
                'start_date'    => '2019-09-01',
                'end_date'      => null,
            ],

            // === U038 ===
            [
                'user_id'       => 'U038',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.33,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U038',
                'company_id'    => 'C009',
                'major_id'      => 11,
                'GPA'           => 3.71,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],

            // === U039 ===
            [
                'user_id'       => 'U039',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.25,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U039',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.86,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-06-01',
            ],

            // === U040 ===
            [
                'user_id'       => 'U040',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.38,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U040',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.79,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],

            // === U041–U050 (pola serupa, variasi data) ===
            [
                'user_id'       => 'U041',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.26,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U041',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.80,
                'start_date'    => '2019-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U042',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.42,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U042',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.83,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U043',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.29,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U043',
                'company_id'    => 'C009',
                'major_id'      => 6,
                'GPA'           => 3.75,
                'start_date'    => '2019-08-01',
                'end_date'      => '2023-06-01',
            ],
            [
                'user_id'       => 'U044',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.34,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U044',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.90,
                'start_date'    => '2018-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U045',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.19,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U045',
                'company_id'    => 'C009',
                'major_id'      => 1,
                'GPA'           => 3.77,
                'start_date'    => '2019-08-01',
                'end_date'      => '2023-06-01',
            ],
            [
                'user_id'       => 'U046',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.41,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U046',
                'company_id'    => 'C009',
                'major_id'      => 13,
                'GPA'           => 3.92,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U047',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.36,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U047',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.76,
                'start_date'    => '2019-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U048',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.35,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U048',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.78,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U049',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.28,
                'start_date'    => '2016-07-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U049',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.87,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-06-01',
            ],
            [
                'user_id'       => 'U050',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.43,
                'start_date'    => '2015-07-01',
                'end_date'      => '2018-05-01',
            ],
            [
                'user_id'       => 'U050',
                'company_id'    => 'C009',
                'major_id'      => 8,
                'GPA'           => 3.89,
                'start_date'    => '2018-08-01',
                'end_date'      => null,
            ],

            // === U051 ===
            [
                'user_id'       => 'U051',
                'company_id'    => 'C009',
                'major_id'      => 4,
                'GPA'           => 3.68,
                'start_date'    => '2013-08-01',
                'end_date'      => '2017-06-01',
            ],
            [
                'user_id'       => 'U051',
                'company_id'    => 'C011',
                'major_id'      => 14,
                'GPA'           => 3.82,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U051',
                'company_id'    => 'C012',
                'major_id'      => 30,
                'GPA'           => 3.91,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U052 ===
            [
                'user_id'       => 'U052',
                'company_id'    => 'C011',
                'major_id'      => 7,
                'GPA'           => 3.72,
                'start_date'    => '2012-08-01',
                'end_date'      => '2016-06-01',
            ],
            [
                'user_id'       => 'U052',
                'company_id'    => 'C012',
                'major_id'      => 18,
                'GPA'           => 3.88,
                'start_date'    => '2017-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U052',
                'company_id'    => 'C013',
                'major_id'      => 32,
                'GPA'           => 3.95,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U053 ===
            [
                'user_id'       => 'U053',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.61,
                'start_date'    => '2013-08-01',
                'end_date'      => '2017-06-01',
            ],
            [
                'user_id'       => 'U053',
                'company_id'    => 'C011',
                'major_id'      => 19,
                'GPA'           => 3.79,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U053',
                'company_id'    => 'C013',
                'major_id'      => 31,
                'GPA'           => 3.92,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U054 ===
            [
                'user_id'       => 'U054',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.59,
                'start_date'    => '2012-08-01',
                'end_date'      => '2016-06-01',
            ],
            [
                'user_id'       => 'U054',
                'company_id'    => 'C012',
                'major_id'      => 15,
                'GPA'           => 3.81,
                'start_date'    => '2017-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U054',
                'company_id'    => 'C013',
                'major_id'      => 33,
                'GPA'           => 3.94,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U055 ===
            [
                'user_id'       => 'U055',
                'company_id'    => 'C011',
                'major_id'      => 10,
                'GPA'           => 3.75,
                'start_date'    => '2013-08-01',
                'end_date'      => '2017-06-01',
            ],
            [
                'user_id'       => 'U055',
                'company_id'    => 'C012',
                'major_id'      => 21,
                'GPA'           => 3.88,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U055',
                'company_id'    => 'C013',
                'major_id'      => 34,
                'GPA'           => 3.97,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U056 ===
            [
                'user_id'       => 'U056',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.69,
                'start_date'    => '2012-08-01',
                'end_date'      => '2016-06-01',
            ],
            [
                'user_id'       => 'U056',
                'company_id'    => 'C011',
                'major_id'      => 16,
                'GPA'           => 3.83,
                'start_date'    => '2017-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U056',
                'company_id'    => 'C013',
                'major_id'      => 32,
                'GPA'           => 3.95,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U057 ===
            [
                'user_id'       => 'U057',
                'company_id'    => 'C009',
                'major_id'      => 1,
                'GPA'           => 3.73,
                'start_date'    => '2013-08-01',
                'end_date'      => '2017-06-01',
            ],
            [
                'user_id'       => 'U057',
                'company_id'    => 'C012',
                'major_id'      => 17,
                'GPA'           => 3.86,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U057',
                'company_id'    => 'C013',
                'major_id'      => 31,
                'GPA'           => 3.94,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // === U058 ===
            [
                'user_id'       => 'U058',
                'company_id'    => 'C011',
                'major_id'      => 9,
                'GPA'           => 3.77,
                'start_date'    => '2012-08-01',
                'end_date'      => '2016-06-01',
            ],
            [
                'user_id'       => 'U058',
                'company_id'    => 'C012',
                'major_id'      => 20,
                'GPA'           => 3.90,
                'start_date'    => '2017-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U058',
                'company_id'    => 'C013',
                'major_id'      => 30,
                'GPA'           => 3.98,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U051',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.78,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U052',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.69,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U053',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.82,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U054',
                'company_id'    => 'C009',
                'major_id'      => 6,
                'GPA'           => 3.74,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U055',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.91,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U056',
                'company_id'    => 'C009',
                'major_id'      => 7,
                'GPA'           => 3.63,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U057',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.80,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U058',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.77,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U059',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.83,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U060',
                'company_id'    => 'C009',
                'major_id'      => 11,
                'GPA'           => 3.72,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U061',
                'company_id'    => 'C009',
                'major_id'      => 12,
                'GPA'           => 3.95,
                'start_date'    => '2020-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U062',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.70,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U063',
                'company_id'    => 'C009',
                'major_id'      => 8,
                'GPA'           => 3.88,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U064',
                'company_id'    => 'C009',
                'major_id'      => 13,
                'GPA'           => 3.66,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U065',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.81,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U066',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.76,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U067',
                'company_id'    => 'C009',
                'major_id'      => 4,
                'GPA'           => 3.67,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U068',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.92,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U069',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.83,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U070',
                'company_id'    => 'C009',
                'major_id'      => 6,
                'GPA'           => 3.74,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U071',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.85,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U072',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.78,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U073',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.90,
                'start_date'    => '2022-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U074',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.73,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U075',
                'company_id'    => 'C009',
                'major_id'      => 12,
                'GPA'           => 3.89,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],
            [
                'user_id'       => 'U075',
                'company_id'    => 'C009',
                'major_id'      => 10,
                'GPA'           => 3.78,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U075',
                'company_id'    => 'C009',
                'major_id'      => 15,
                'GPA'           => 3.91,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U076
            [
                'user_id'       => 'U076',
                'company_id'    => 'C009',
                'major_id'      => 4,
                'GPA'           => 3.64,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-07-01',
            ],
            [
                'user_id'       => 'U076',
                'company_id'    => 'C009',
                'major_id'      => 18,
                'GPA'           => 3.85,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U077
            [
                'user_id'       => 'U077',
                'company_id'    => 'C009',
                'major_id'      => 6,
                'GPA'           => 3.71,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-05-01',
            ],
            [
                'user_id'       => 'U077',
                'company_id'    => 'C009',
                'major_id'      => 19,
                'GPA'           => 3.94,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U078
            [
                'user_id'       => 'U078',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.68,
                'start_date'    => '2017-09-01',
                'end_date'      => '2021-08-01',
            ],
            [
                'user_id'       => 'U078',
                'company_id'    => 'C009',
                'major_id'      => 17,
                'GPA'           => 3.88,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U079
            [
                'user_id'       => 'U079',
                'company_id'    => 'C009',
                'major_id'      => 7,
                'GPA'           => 3.82,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-07-01',
            ],
            [
                'user_id'       => 'U079',
                'company_id'    => 'C009',
                'major_id'      => 20,
                'GPA'           => 3.95,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U080
            [
                'user_id'       => 'U080',
                'company_id'    => 'C009',
                'major_id'      => 8,
                'GPA'           => 3.75,
                'start_date'    => '2017-09-01',
                'end_date'      => '2021-08-01',
            ],
            [
                'user_id'       => 'U080',
                'company_id'    => 'C009',
                'major_id'      => 16,
                'GPA'           => 3.89,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U081
            [
                'user_id'       => 'U081',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.77,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U081',
                'company_id'    => 'C009',
                'major_id'      => 14,
                'GPA'           => 3.93,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U082
            [
                'user_id'       => 'U082',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.80,
                'start_date'    => '2017-08-01',
                'end_date'      => '2021-07-01',
            ],
            [
                'user_id'       => 'U082',
                'company_id'    => 'C009',
                'major_id'      => 15,
                'GPA'           => 3.90,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U083
            [
                'user_id'       => 'U083',
                'company_id'    => 'C009',
                'major_id'      => 1,
                'GPA'           => 3.69,
                'start_date'    => '2017-09-01',
                'end_date'      => '2021-08-01',
            ],
            [
                'user_id'       => 'U083',
                'company_id'    => 'C009',
                'major_id'      => 19,
                'GPA'           => 3.96,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U084
            [
                'user_id'       => 'U084',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.81,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-07-01',
            ],
            [
                'user_id'       => 'U084',
                'company_id'    => 'C009',
                'major_id'      => 17,
                'GPA'           => 3.92,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U085
            [
                'user_id'       => 'U085',
                'company_id'    => 'C009',
                'major_id'      => 12,
                'GPA'           => 3.83,
                'start_date'    => '2017-09-01',
                'end_date'      => '2021-07-01',
            ],
            [
                'user_id'       => 'U085',
                'company_id'    => 'C009',
                'major_id'      => 18,
                'GPA'           => 3.97,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],
            // U086
            [
                'user_id'       => 'U086',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.70,
                'start_date'    => '2015-08-01',
                'end_date'      => '2019-06-01',
            ],
            [
                'user_id'       => 'U086',
                'company_id'    => 'C009',
                'major_id'      => 16,
                'GPA'           => 3.85,
                'start_date'    => '2019-09-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U086',
                'company_id'    => 'C009',
                'major_id'      => 21,
                'GPA'           => 3.94,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U087
            [
                'user_id'       => 'U087',
                'company_id'    => 'C009',
                'major_id'      => 6,
                'GPA'           => 3.68,
                'start_date'    => '2014-09-01',
                'end_date'      => '2018-06-01',
            ],
            [
                'user_id'       => 'U087',
                'company_id'    => 'C009',
                'major_id'      => 19,
                'GPA'           => 3.84,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U087',
                'company_id'    => 'C009',
                'major_id'      => 22,
                'GPA'           => 3.96,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],

            // U088
            [
                'user_id'       => 'U088',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.72,
                'start_date'    => '2016-08-01',
                'end_date'      => '2020-07-01',
            ],
            [
                'user_id'       => 'U088',
                'company_id'    => 'C009',
                'major_id'      => 17,
                'GPA'           => 3.86,
                'start_date'    => '2020-09-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U088',
                'company_id'    => 'C009',
                'major_id'      => 21,
                'GPA'           => 3.93,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U089
            [
                'user_id'       => 'U089',
                'company_id'    => 'C009',
                'major_id'      => 5,
                'GPA'           => 3.75,
                'start_date'    => '2015-09-01',
                'end_date'      => '2019-07-01',
            ],
            [
                'user_id'       => 'U089',
                'company_id'    => 'C009',
                'major_id'      => 15,
                'GPA'           => 3.89,
                'start_date'    => '2019-09-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U089',
                'company_id'    => 'C009',
                'major_id'      => 22,
                'GPA'           => 3.98,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U090
            [
                'user_id'       => 'U090',
                'company_id'    => 'C009',
                'major_id'      => 8,
                'GPA'           => 3.79,
                'start_date'    => '2014-08-01',
                'end_date'      => '2018-06-01',
            ],
            [
                'user_id'       => 'U090',
                'company_id'    => 'C009',
                'major_id'      => 14,
                'GPA'           => 3.91,
                'start_date'    => '2018-09-01',
                'end_date'      => '2020-06-01',
            ],
            [
                'user_id'       => 'U090',
                'company_id'    => 'C009',
                'major_id'      => 21,
                'GPA'           => 3.99,
                'start_date'    => '2020-09-01',
                'end_date'      => null,
            ],
            // U091 - 1 pendidikan (Bachelor)
            [
                'user_id'       => 'U091',
                'company_id'    => 'C011',
                'major_id'      => 27,
                'GPA'           => 3.72,
                'start_date'    => '2019-08-01',
                'end_date'      => null,
            ],

            // U092 - Highschool + Bachelor
            [
                'user_id'       => 'U092',
                'company_id'    => 'C010',
                'major_id'      => 23,
                'GPA'           => 3.60,
                'start_date'    => '2014-07-01',
                'end_date'      => '2017-05-01',
            ],
            [
                'user_id'       => 'U092',
                'company_id'    => 'C009',
                'major_id'      => 9,
                'GPA'           => 3.81,
                'start_date'    => '2017-09-01',
                'end_date'      => '2021-06-01',
            ],

            // U093 - Bachelor + Master
            [
                'user_id'       => 'U093',
                'company_id'    => 'C009',
                'major_id'      => 11,
                'GPA'           => 3.77,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U093',
                'company_id'    => 'C009',
                'major_id'      => 17,
                'GPA'           => 3.90,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U094 - Bachelor
            [
                'user_id'       => 'U094',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.66,
                'start_date'    => '2020-08-01',
                'end_date'      => null,
            ],

            // U095 - Diploma + Bachelor
            [
                'user_id'       => 'U095',
                'company_id'    => 'C010',
                'major_id'      => 25,
                'GPA'           => 3.58,
                'start_date'    => '2016-06-01',
                'end_date'      => '2019-05-01',
            ],
            [
                'user_id'       => 'U095',
                'company_id'    => 'C009',
                'major_id'      => 3,
                'GPA'           => 3.83,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-06-01',
            ],

            // U096 - Bachelor + Master + Doctor
            [
                'user_id'       => 'U096',
                'company_id'    => 'C009',
                'major_id'      => 2,
                'GPA'           => 3.71,
                'start_date'    => '2015-08-01',
                'end_date'      => '2019-06-01',
            ],
            [
                'user_id'       => 'U096',
                'company_id'    => 'C009',
                'major_id'      => 18,
                'GPA'           => 3.88,
                'start_date'    => '2019-09-01',
                'end_date'      => '2021-06-01',
            ],
            [
                'user_id'       => 'U096',
                'company_id'    => 'C009',
                'major_id'      => 22,
                'GPA'           => 3.97,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U097 - 1 pendidikan (Master)
            [
                'user_id'       => 'U097',
                'company_id'    => 'C011',
                'major_id'      => 33,
                'GPA'           => 3.89,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U098 - Highschool + Diploma
            [
                'user_id'       => 'U098',
                'company_id'    => 'C010',
                'major_id'      => 24,
                'GPA'           => 3.65,
                'start_date'    => '2013-07-01',
                'end_date'      => '2016-05-01',
            ],
            [
                'user_id'       => 'U098',
                'company_id'    => 'C010',
                'major_id'      => 25,
                'GPA'           => 3.79,
                'start_date'    => '2016-09-01',
                'end_date'      => '2019-07-01',
            ],

            // U099 - Bachelor
            [
                'user_id'       => 'U099',
                'company_id'    => 'C009',
                'major_id'      => 7,
                'GPA'           => 3.80,
                'start_date'    => '2021-08-01',
                'end_date'      => null,
            ],

            // U100 - Bachelor + Master
            [
                'user_id'       => 'U100',
                'company_id'    => 'C011',
                'major_id'      => 29,
                'GPA'           => 3.75,
                'start_date'    => '2018-08-01',
                'end_date'      => '2022-06-01',
            ],
            [
                'user_id'       => 'U100',
                'company_id'    => 'C011',
                'major_id'      => 36,
                'GPA'           => 3.92,
                'start_date'    => '2022-09-01',
                'end_date'      => null,
            ],

            // U101 - 1 pendidikan (Doctor)
            [
                'user_id'       => 'U101',
                'company_id'    => 'C009',
                'major_id'      => 21,
                'GPA'           => 3.95,
                'start_date'    => '2021-09-01',
                'end_date'      => null,
            ],

            // U102 - Bachelor + Master
            [
                'user_id'       => 'U102',
                'company_id'    => 'C011',
                'major_id'      => 26,
                'GPA'           => 3.79,
                'start_date'    => '2019-09-01',
                'end_date'      => '2023-07-01',
            ],
            [
                'user_id'       => 'U102',
                'company_id'    => 'C011',
                'major_id'      => 32,
                'GPA'           => 3.93,
                'start_date'    => '2023-09-01',
                'end_date'      => null,
            ],

        ]);
    }
}



