<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserExperienceSeeder extends Seeder
{
    public function run(): void
    {
        $experienceSeeder =
        [
            ['user_id' => 'U001', 'company_id' => 'C001', 'title' => 'Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-07-01', 'end_date' => null],
            ['user_id' => 'U002', 'company_id' => 'C002', 'title' => 'Front End Developer', 'employment_id' => 'IN', 'mode_id' => 'RE', 'start_date' => '2024-01-15', 'end_date' => '2024-06-15'],
            ['user_id' => 'U003', 'company_id' => 'C003', 'title' => 'Back End Developer', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2022-03-01', 'end_date' => null],
            ['user_id' => 'U004', 'company_id' => 'C004', 'title' => 'UI/UX Designer', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2024-09-01', 'end_date' => null],
            ['user_id' => 'U005', 'company_id' => 'C005', 'title' => 'Mobile Application Developer', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2025-08-01', 'end_date' => '2027-08-01'],
            ['user_id' => 'U006', 'company_id' => 'C006', 'title' => 'Project Manager', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2021-01-01', 'end_date' => null],
            ['user_id' => 'U007', 'company_id' => 'C007', 'title' => 'Full Stack Developer', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2023-05-01', 'end_date' => '2024-05-01'],
            ['user_id' => 'U008', 'company_id' => 'C008', 'title' => 'Data Analyst', 'employment_id' => 'PT', 'mode_id' => 'HY', 'start_date' => '2024-02-01', 'end_date' => null],
            ['user_id' => 'U009', 'company_id' => 'C009', 'title' => 'Research Assistant', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2023-09-01', 'end_date' => '2024-03-01'],
            ['user_id' => 'U010', 'company_id' => 'C010', 'title' => 'IT Support Staff', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2022-07-01', 'end_date' => null],
            ['user_id' => 'U011', 'company_id' => 'C011', 'title' => 'Machine Learning Researcher', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2021-06-01', 'end_date' => '2023-06-01'],
            ['user_id' => 'U012', 'company_id' => 'C012', 'title' => 'Game Developer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2020-01-01', 'end_date' => null],
            ['user_id' => 'U013', 'company_id' => 'C013', 'title' => 'Blockchain Specialist', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2023-03-15', 'end_date' => null],
            ['user_id' => 'U014', 'company_id' => 'C005', 'title' => 'iOS Developer', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2024-01-01', 'end_date' => '2024-12-31'],
            ['user_id' => 'U015', 'company_id' => 'C001', 'title' => 'Cloud Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2022-05-01', 'end_date' => null],
            ['user_id' => 'U016', 'company_id' => 'C008', 'title' => 'DevOps Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2023-04-01', 'end_date' => '2024-04-01'],
            ['user_id' => 'U017', 'company_id' => 'C012', 'title' => '3D Environment Artist', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2024-02-01', 'end_date' => null],
            ['user_id' => 'U018', 'company_id' => 'C007', 'title' => 'Product Designer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-06-01', 'end_date' => null],
            ['user_id' => 'U019', 'company_id' => 'C002', 'title' => 'Data Scientist', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2021-11-01', 'end_date' => null],
            ['user_id' => 'U020', 'company_id' => 'C009', 'title' => 'Teaching Assistant', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2025-02-01', 'end_date' => null],
            ['user_id' => 'U021', 'company_id' => 'C001', 'title' => 'Junior Backend Developer', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2024-02-01', 'end_date' => '2024-08-01'],
            ['user_id' => 'U021', 'company_id' => 'C013', 'title' => 'Software Engineering Intern', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2025-01-01', 'end_date' => null],
            ['user_id' => 'U022', 'company_id' => 'C007', 'title' => 'Full Stack Web Developer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U022', 'company_id' => 'C006', 'title' => 'Technical Product Manager', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-01-01', 'end_date' => '2025-01-01'],
            ['user_id' => 'U023', 'company_id' => 'C002', 'title' => 'Data Science Associate', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2024-05-01', 'end_date' => null],
            ['user_id' => 'U024', 'company_id' => 'C005', 'title' => 'iOS Application Engineer', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2021-10-01', 'end_date' => null],
            ['user_id' => 'U024', 'company_id' => 'C004', 'title' => 'Digital Media Specialist', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => '2024-01-01'],
            ['user_id' => 'U025', 'company_id' => 'C012', 'title' => 'Game System Designer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2020-07-01', 'end_date' => null],
            ['user_id' => 'U025', 'company_id' => 'C011', 'title' => 'AI Research Assistant', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-08-01', 'end_date' => '2023-02-01'],
            ['user_id' => 'U026', 'company_id' => 'C006', 'title' => 'Product Operations Analyst', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-05-01', 'end_date' => null],
            ['user_id' => 'U027', 'company_id' => 'C003', 'title' => 'Social Media Strategist', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2022-11-01', 'end_date' => null],
            ['user_id' => 'U028', 'company_id' => 'C009', 'title' => 'Assistant Lecturer', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2024-02-01', 'end_date' => null],
            ['user_id' => 'U029', 'company_id' => 'C008', 'title' => 'Quality Assurance Tester', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2023-09-01', 'end_date' => '2024-09-01'],
            ['user_id' => 'U029', 'company_id' => 'C007', 'title' => 'Technical Support Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-10-01', 'end_date' => null],
            ['user_id' => 'U030', 'company_id' => 'C001', 'title' => 'Cloud Infrastructure Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2021-01-01', 'end_date' => null],
            ['user_id' => 'U030', 'company_id' => 'C005', 'title' => 'Software Development Lead', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2024-02-01', 'end_date' => null],
            ['user_id' => 'U031', 'company_id' => 'C002', 'title' => 'Blockchain Solutions Architect', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2023-06-01', 'end_date' => null],
            ['user_id' => 'U032', 'company_id' => 'C013', 'title' => 'Information Security Analyst', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2022-09-01', 'end_date' => null],
            ['user_id' => 'U033', 'company_id' => 'C012', 'title' => 'Gameplay Programmer', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2021-05-01', 'end_date' => null],
            ['user_id' => 'U034', 'company_id' => 'C009', 'title' => 'Database System Tutor', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U035', 'company_id' => 'C007', 'title' => 'Data Analytics Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2025-03-01', 'end_date' => null],
            ['user_id' => 'U036', 'company_id' => 'C010', 'title' => 'Education Technology Assistant', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2023-08-01', 'end_date' => null],
            ['user_id' => 'U037', 'company_id' => 'C008', 'title' => 'Mobile App Tester', 'employment_id' => 'IN', 'mode_id' => 'RE', 'start_date' => '2024-05-01', 'end_date' => '2024-11-01'],
            ['user_id' => 'U037', 'company_id' => 'C006', 'title' => 'Business Development Analyst', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-01-01', 'end_date' => null],
            ['user_id' => 'U038', 'company_id' => 'C011', 'title' => 'Computational Research Intern', 'employment_id' => 'IN', 'mode_id' => 'RE', 'start_date' => '2023-02-01', 'end_date' => '2023-08-01'],
            ['user_id' => 'U039', 'company_id' => 'C004', 'title' => 'Community Engagement Specialist', 'employment_id' => 'PT', 'mode_id' => 'HY', 'start_date' => '2024-04-01', 'end_date' => null],
            ['user_id' => 'U040', 'company_id' => 'C003', 'title' => 'Content Marketing Strategist', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2021-10-01', 'end_date' => null],
            ['user_id' => 'U040', 'company_id' => 'C005', 'title' => 'UI Design Consultant', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-03-01', 'end_date' => null],
            ['user_id' => 'U041', 'company_id' => 'C001', 'title' => 'Software Development Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2023-02-01', 'end_date' => '2023-08-01'],
            ['user_id' => 'U041', 'company_id' => 'C006', 'title' => 'Associate Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-10-01', 'end_date' => null],
            ['user_id' => 'U042', 'company_id' => 'C009', 'title' => 'Lab Assistant', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2024-01-01', 'end_date' => '2024-06-01'],
            ['user_id' => 'U042', 'company_id' => 'C010', 'title' => 'Academic Technology Specialist', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2024-07-01', 'end_date' => null],
            ['user_id' => 'U043', 'company_id' => 'C007', 'title' => 'Frontend Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2022-11-01', 'end_date' => null],
            ['user_id' => 'U043', 'company_id' => 'C008', 'title' => 'Software QA Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-01-01', 'end_date' => '2024-12-01'],
            ['user_id' => 'U044', 'company_id' => 'C012', 'title' => 'Game Design Intern', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2023-03-01', 'end_date' => '2023-09-01'],
            ['user_id' => 'U044', 'company_id' => 'C012', 'title' => 'Gameplay Systems Designer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-10-01', 'end_date' => null],
            ['user_id' => 'U045', 'company_id' => 'C005', 'title' => 'Mobile Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2021-08-01', 'end_date' => null],
            ['user_id' => 'U045', 'company_id' => 'C001', 'title' => 'Cloud Platform Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2023-09-01', 'end_date' => '2024-09-01'],
            ['user_id' => 'U046', 'company_id' => 'C006', 'title' => 'Operations Data Analyst', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2022-06-01', 'end_date' => null],
            ['user_id' => 'U046', 'company_id' => 'C013', 'title' => 'IT Compliance Officer', 'employment_id' => 'CO', 'mode_id' => 'OS', 'start_date' => '2024-03-01', 'end_date' => '2025-03-01'],
            ['user_id' => 'U047', 'company_id' => 'C008', 'title' => 'Backend Web Developer', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2023-04-01', 'end_date' => '2023-10-01'],
            ['user_id' => 'U047', 'company_id' => 'C007', 'title' => 'Site Reliability Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U048', 'company_id' => 'C002', 'title' => 'Marketing Campaign Manager', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2021-10-01', 'end_date' => null],
            ['user_id' => 'U048', 'company_id' => 'C004', 'title' => 'Content Production Lead', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2023-05-01', 'end_date' => null],
            ['user_id' => 'U048', 'company_id' => 'C003', 'title' => 'Brand Strategy Specialist', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2024-07-01', 'end_date' => null],
            ['user_id' => 'U049', 'company_id' => 'C009', 'title' => 'Teaching Laboratory Assistant', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2023-09-01', 'end_date' => '2024-06-01'],
            ['user_id' => 'U049', 'company_id' => 'C011', 'title' => 'Machine Learning Researcher', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-07-01', 'end_date' => null],
            ['user_id' => 'U050', 'company_id' => 'C012', 'title' => '3D Animation Artist', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2020-01-01', 'end_date' => null],
            ['user_id' => 'U050', 'company_id' => 'C013', 'title' => 'Technology Risk Analyst', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-02-01', 'end_date' => '2025-02-01'],
            ['user_id' => 'U051', 'company_id' => 'C001', 'title' => 'Systems Integration Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U051', 'company_id' => 'C005', 'title' => 'Software Engineering Manager', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2024-08-01', 'end_date' => null],
            ['user_id' => 'U052', 'company_id' => 'C006', 'title' => 'Data Governance Specialist', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2023-06-01', 'end_date' => '2024-06-01'],
            ['user_id' => 'U052', 'company_id' => 'C007', 'title' => 'Software Implementation Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2024-08-01', 'end_date' => null],
            ['user_id' => 'U053', 'company_id' => 'C008', 'title' => 'Junior Mobile Developer', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2024-01-01', 'end_date' => '2024-07-01'],
            ['user_id' => 'U053', 'company_id' => 'C006', 'title' => 'Product Management Associate', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-08-01', 'end_date' => null],
            ['user_id' => 'U054', 'company_id' => 'C009', 'title' => 'Academic Research Assistant', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-08-01', 'end_date' => '2023-02-01'],
            ['user_id' => 'U054', 'company_id' => 'C010', 'title' => 'Educational Program Coordinator', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-04-01', 'end_date' => null],
            ['user_id' => 'U055', 'company_id' => 'C013', 'title' => 'Financial Systems Analyst', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2021-06-01', 'end_date' => null],
            ['user_id' => 'U055', 'company_id' => 'C006', 'title' => 'Digital Transformation Consultant', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2023-08-01', 'end_date' => '2024-08-01'],
            ['user_id' => 'U055', 'company_id' => 'C007', 'title' => 'Business Process Analyst', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-09-01', 'end_date' => null],
            ['user_id' => 'U056', 'company_id' => 'C011', 'title' => 'AI Research Fellow', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2022-03-01', 'end_date' => null],
            ['user_id' => 'U056', 'company_id' => 'C012', 'title' => 'Technical Game Artist', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-05-01', 'end_date' => '2025-05-01'],
            ['user_id' => 'U057', 'company_id' => 'C003', 'title' => 'Digital Advertising Strategist', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2021-01-01', 'end_date' => null],
            ['user_id' => 'U057', 'company_id' => 'C004', 'title' => 'Community Partnership Lead', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-02-01', 'end_date' => null],
            ['user_id' => 'U058', 'company_id' => 'C005', 'title' => 'Senior Software Architect', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2020-04-01', 'end_date' => null],
            ['user_id' => 'U058', 'company_id' => 'C001', 'title' => 'Technical Program Manager', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-06-01', 'end_date' => null],
            ['user_id' => 'U059', 'company_id' => 'C007', 'title' => 'Junior Software Developer', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2024-02-01', 'end_date' => '2024-08-01'],
            ['user_id' => 'U059', 'company_id' => 'C008', 'title' => 'Backend Development Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-09-01', 'end_date' => null],
            ['user_id' => 'U060', 'company_id' => 'C013', 'title' => 'Data Compliance Analyst', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2022-10-01', 'end_date' => null],
            ['user_id' => 'U060', 'company_id' => 'C006', 'title' => 'Digital Product Owner', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-03-01', 'end_date' => null],
            ['user_id' => 'U061', 'company_id' => 'C001', 'title' => 'Software Engineer Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-06-01', 'end_date' => '2022-12-01'],
            ['user_id' => 'U061', 'company_id' => 'C007', 'title' => 'Frontend Web Developer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2023-02-01', 'end_date' => null],
            ['user_id' => 'U061', 'company_id' => 'C006', 'title' => 'Technical Lead Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-05-01', 'end_date' => '2025-05-01'],
            ['user_id' => 'U061', 'company_id' => 'C013', 'title' => 'Information Security Consultant', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2025-06-01', 'end_date' => null],
            ['user_id' => 'U062', 'company_id' => 'C009', 'title' => 'Teaching Assistant', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2022-08-01', 'end_date' => '2023-02-01'],
            ['user_id' => 'U062', 'company_id' => 'C010', 'title' => 'Education Technology Assistant', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2023-03-01', 'end_date' => '2023-09-01'],
            ['user_id' => 'U062', 'company_id' => 'C011', 'title' => 'Data Science Researcher', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U062', 'company_id' => 'C005', 'title' => 'Machine Learning Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2025-02-01', 'end_date' => null],
            ['user_id' => 'U063', 'company_id' => 'C008', 'title' => 'Backend Developer Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-07-01', 'end_date' => '2023-01-01'],
            ['user_id' => 'U063', 'company_id' => 'C007', 'title' => 'Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U063', 'company_id' => 'C006', 'title' => 'DevOps Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-04-01', 'end_date' => '2025-04-01'],
            ['user_id' => 'U063', 'company_id' => 'C002', 'title' => 'Cloud Infrastructure Architect', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2025-06-01', 'end_date' => null],
            ['user_id' => 'U064', 'company_id' => 'C012', 'title' => 'Junior Game Developer', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-03-01', 'end_date' => '2022-09-01'],
            ['user_id' => 'U064', 'company_id' => 'C012', 'title' => 'Gameplay Programmer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-01-01', 'end_date' => null],
            ['user_id' => 'U064', 'company_id' => 'C005', 'title' => 'AR/VR Developer', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-03-01', 'end_date' => '2025-03-01'],
            ['user_id' => 'U064', 'company_id' => 'C008', 'title' => 'Software Engineer Lead', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-04-01', 'end_date' => null],
            ['user_id' => 'U065', 'company_id' => 'C003', 'title' => 'Marketing Data Analyst', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2022-04-01', 'end_date' => '2022-10-01'],
            ['user_id' => 'U065', 'company_id' => 'C004', 'title' => 'Digital Marketing Associate', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2023-01-01', 'end_date' => '2023-07-01'],
            ['user_id' => 'U065', 'company_id' => 'C002', 'title' => 'Content Strategy Manager', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U065', 'company_id' => 'C006', 'title' => 'Product Operations Manager', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2025-03-01', 'end_date' => null],
            ['user_id' => 'U066', 'company_id' => 'C009', 'title' => 'Assistant Lecturer', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2022-09-01', 'end_date' => '2023-03-01'],
            ['user_id' => 'U066', 'company_id' => 'C010', 'title' => 'Education Program Assistant', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2023-04-01', 'end_date' => '2023-10-01'],
            ['user_id' => 'U066', 'company_id' => 'C011', 'title' => 'Data Research Specialist', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U066', 'company_id' => 'C005', 'title' => 'AI Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-02-01', 'end_date' => null],
            ['user_id' => 'U067', 'company_id' => 'C006', 'title' => 'Operations Analyst Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-05-01', 'end_date' => '2022-11-01'],
            ['user_id' => 'U067', 'company_id' => 'C007', 'title' => 'Business Operations Associate', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => null],
            ['user_id' => 'U067', 'company_id' => 'C008', 'title' => 'Product Management Specialist', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-04-01', 'end_date' => '2025-04-01'],
            ['user_id' => 'U067', 'company_id' => 'C013', 'title' => 'Business Intelligence Manager', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2025-06-01', 'end_date' => null],
            ['user_id' => 'U068', 'company_id' => 'C012', 'title' => 'Junior 3D Artist', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-06-01', 'end_date' => '2022-12-01'],
            ['user_id' => 'U068', 'company_id' => 'C012', 'title' => 'Senior Environment Artist', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-02-01', 'end_date' => null],
            ['user_id' => 'U068', 'company_id' => 'C005', 'title' => 'AR Game Developer', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-06-01', 'end_date' => '2025-06-01'],
            ['user_id' => 'U068', 'company_id' => 'C001', 'title' => 'Graphics Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-07-01', 'end_date' => null],
            ['user_id' => 'U069', 'company_id' => 'C013', 'title' => 'Banking Technology Analyst', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-02-01', 'end_date' => '2022-08-01'],
            ['user_id' => 'U069', 'company_id' => 'C006', 'title' => 'IT Business Analyst', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-01-01', 'end_date' => null],
            ['user_id' => 'U069', 'company_id' => 'C007', 'title' => 'Project Implementation Lead', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-03-01', 'end_date' => '2025-03-01'],
            ['user_id' => 'U069', 'company_id' => 'C008', 'title' => 'Digital Product Manager', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-04-01', 'end_date' => null],
            ['user_id' => 'U070', 'company_id' => 'C002', 'title' => 'Marketing Assistant Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-03-01', 'end_date' => '2022-09-01'],
            ['user_id' => 'U070', 'company_id' => 'C003', 'title' => 'Social Media Coordinator', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => '2023-09-01'],
            ['user_id' => 'U070', 'company_id' => 'C004', 'title' => 'Creative Content Producer', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U070', 'company_id' => 'C006', 'title' => 'Digital Brand Manager', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-03-01', 'end_date' => null],
            ['user_id' => 'U071', 'company_id' => 'C005', 'title' => 'iOS Developer Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-06-01', 'end_date' => '2022-12-01'],
            ['user_id' => 'U071', 'company_id' => 'C005', 'title' => 'Mobile Application Engineer', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U071', 'company_id' => 'C001', 'title' => 'Software Engineering Lead', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-05-01', 'end_date' => null],
            ['user_id' => 'U071', 'company_id' => 'C013', 'title' => 'Cloud Solutions Architect', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2025-06-01', 'end_date' => null],
            ['user_id' => 'U072', 'company_id' => 'C012', 'title' => 'Game Developer Intern', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-08-01', 'end_date' => '2023-02-01'],
            ['user_id' => 'U072', 'company_id' => 'C012', 'title' => 'Lead Gameplay Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U072', 'company_id' => 'C005', 'title' => 'AR Application Developer', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-04-01', 'end_date' => '2025-04-01'],
            ['user_id' => 'U072', 'company_id' => 'C001', 'title' => 'Senior Software Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-05-01', 'end_date' => null],
            ['user_id' => 'U073', 'company_id' => 'C009', 'title' => 'Teaching Lab Assistant', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2022-09-01', 'end_date' => '2023-03-01'],
            ['user_id' => 'U073', 'company_id' => 'C010', 'title' => 'Education Development Intern', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2023-04-01', 'end_date' => '2023-10-01'],
            ['user_id' => 'U073', 'company_id' => 'C011', 'title' => 'AI Research Assistant', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U073', 'company_id' => 'C005', 'title' => 'Machine Learning Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2025-02-01', 'end_date' => null],
            ['user_id' => 'U074', 'company_id' => 'C006', 'title' => 'Junior Business Analyst', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-05-01', 'end_date' => '2022-11-01'],
            ['user_id' => 'U074', 'company_id' => 'C007', 'title' => 'Operations Associate', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => null],
            ['user_id' => 'U074', 'company_id' => 'C008', 'title' => 'Data Analytics Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-03-01', 'end_date' => '2025-03-01'],
            ['user_id' => 'U074', 'company_id' => 'C013', 'title' => 'Financial Data Manager', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2025-05-01', 'end_date' => null],
            ['user_id' => 'U075', 'company_id' => 'C002', 'title' => 'Marketing Strategy Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-03-01', 'end_date' => '2022-09-01'],
            ['user_id' => 'U075', 'company_id' => 'C003', 'title' => 'Social Media Manager', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => '2023-09-01'],
            ['user_id' => 'U075', 'company_id' => 'C004', 'title' => 'Content Creation Lead', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U075', 'company_id' => 'C006', 'title' => 'Brand Experience Manager', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-03-01', 'end_date' => null],
            ['user_id' => 'U076', 'company_id' => 'C005', 'title' => 'Software Engineer Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-06-01', 'end_date' => '2022-12-01'],
            ['user_id' => 'U076', 'company_id' => 'C005', 'title' => 'Full Stack Developer', 'employment_id' => 'FT', 'mode_id' => 'OS', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U076', 'company_id' => 'C001', 'title' => 'Backend Software Engineer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-05-01', 'end_date' => null],
            ['user_id' => 'U076', 'company_id' => 'C013', 'title' => 'Cloud Platform Specialist', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2025-06-01', 'end_date' => null],
            ['user_id' => 'U077', 'company_id' => 'C012', 'title' => 'Gameplay Developer Intern', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-08-01', 'end_date' => '2023-02-01'],
            ['user_id' => 'U077', 'company_id' => 'C012', 'title' => 'Game Design Engineer', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2023-03-01', 'end_date' => null],
            ['user_id' => 'U077', 'company_id' => 'C005', 'title' => 'Augmented Reality Developer', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-04-01', 'end_date' => '2025-04-01'],
            ['user_id' => 'U077', 'company_id' => 'C001', 'title' => 'Senior Software Architect', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-05-01', 'end_date' => null],
            ['user_id' => 'U078', 'company_id' => 'C009', 'title' => 'Research Assistant Intern', 'employment_id' => 'IN', 'mode_id' => 'OS', 'start_date' => '2022-07-01', 'end_date' => '2022-12-01'],
            ['user_id' => 'U078', 'company_id' => 'C010', 'title' => 'Academic Support Assistant', 'employment_id' => 'PT', 'mode_id' => 'OS', 'start_date' => '2023-01-01', 'end_date' => '2023-06-01'],
            ['user_id' => 'U078', 'company_id' => 'C011', 'title' => 'AI Research Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2024-02-01', 'end_date' => null],
            ['user_id' => 'U078', 'company_id' => 'C005', 'title' => 'Computer Vision Specialist', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2025-03-01', 'end_date' => null],
            ['user_id' => 'U079', 'company_id' => 'C006', 'title' => 'Data Analyst Intern', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-05-01', 'end_date' => '2022-11-01'],
            ['user_id' => 'U079', 'company_id' => 'C007', 'title' => 'Product Data Analyst', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => null],
            ['user_id' => 'U079', 'company_id' => 'C008', 'title' => 'Machine Learning Developer', 'employment_id' => 'CO', 'mode_id' => 'HY', 'start_date' => '2024-03-01', 'end_date' => '2025-03-01'],
            ['user_id' => 'U079', 'company_id' => 'C013', 'title' => 'Financial Systems Engineer', 'employment_id' => 'FT', 'mode_id' => 'RE', 'start_date' => '2025-05-01', 'end_date' => null],
            ['user_id' => 'U080', 'company_id' => 'C002', 'title' => 'Social Media Analyst', 'employment_id' => 'IN', 'mode_id' => 'HY', 'start_date' => '2022-03-01', 'end_date' => '2022-09-01'],
            ['user_id' => 'U080', 'company_id' => 'C003', 'title' => 'Marketing Campaign Coordinator', 'employment_id' => 'PT', 'mode_id' => 'RE', 'start_date' => '2023-01-01', 'end_date' => '2023-09-01'],
            ['user_id' => 'U080', 'company_id' => 'C004', 'title' => 'Brand Strategy Manager', 'employment_id' => 'CO', 'mode_id' => 'RE', 'start_date' => '2024-01-01', 'end_date' => null],
            ['user_id' => 'U080', 'company_id' => 'C006', 'title' => 'Head of Marketing Operations', 'employment_id' => 'FT', 'mode_id' => 'HY', 'start_date' => '2025-03-01', 'end_date' => null],

        ];

        DB::table('user_experiences')->insert($experienceSeeder);
    }
}


